### ISSUE TITLE
UnicodeDecodeError for Asian Language such as CJK

### ISSUE THREAD

**Issue by Thunderbird2086** [im85288/service.upnext#106]
OS: MacOS 10.12.6
Kodi : Version 18.4. (20190831-3ade758ceb)
UpNext : 1.0.6
```
2019-12-02 21:55:09.484 T:123145514586112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/Users/allen/Library/Application Support/Kodi/addons/service.upnext/service.py", line 8, in <module>
                                                Monitor().run()
                                              File "/Users/allen/Library/Application Support/Kodi/addons/service.upnext/resources/lib/monitor.py", line 68, in run
                                                self.playback_manager.launch_up_next()
                                              File "/Users/allen/Library/Application Support/Kodi/addons/service.upnext/resources/lib/playbackmanager.py", line 40, in launch_up_next
                                                self.clock_twelve = 'm' in xbmc.getInfoLabel('System.Time').lower()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
```
Please advise

**Comment by Thunderbird2086** [comment]
I have figured out what cause this issue. 
When I used Kodi in English mode, it worked perfect. 
But, it threw the exception above when the language settings is either Japanese or Korean.
I have impressions that it may throws if the language setting is Chinese too.

**Comment by dagwieers** [comment]
This is with v1.0.6 ?

**Comment by Thunderbird2086** [comment]
Yes!

**Comment by Thunderbird2086** [comment]
confirmed that it threw the exception for Chinese too.  😢

**Comment by dagwieers** [comment]
I see that this is probably not the best way to see if this is a 24h format or not, but can you try this as a temporary workaround:
```
from .statichelper import to_unicode
self.clock_twelve = 'm' in to_unicode(xbmc.getInfoLabel('System.Time')).lower()
```

Let me make a PR out of this.

**Comment by Thunderbird2086** [comment]
Yes, I agree with you @dagwieers

**Comment by dagwieers** [comment]
BTW v1.0.6 has not been released, so we can still fix this :-) The issue is caused by our work to make Up Next compatible with Python 3 by using unicode everywhere. But since Kodi Leia is not Unicode-aware (at least not in most parts) this affects Python 2 as well. So this is not unexpected, and your feedback is very valuable ;-)

**Comment by Thunderbird2086** [comment]
You're welcome! 
And, I think checking 'm' is not a good idea for CJK.  We need to come up with clean solution.
For instance, AM is `午前` and PM is `午後` in Japanese.

**Comment by Thunderbird2086** [comment]
The workaround still failed though, @dagwieers  😢

**Comment by dagwieers** [comment]
@Thunderbird2086 Then let's look at a proper solution, hold on :-)

**Comment by dagwieers** [comment]
Do you get the exact same error ? Because that's not what I would be expecting.

If you simply applied the change on Kodi, you need to disable and then enable Up Next to restart the service, otherwise the old code is being run. (Or you can also reboot)

**Comment by Thunderbird2086** [comment]
Here is my code snippet.
```
41         self.log('time=(%s)' % xbmc.getInfoLabel('System.Time').lower(), 0)     
42         # self.clock_twelve = 'm' in xbmc.getInfoLabel('System.Time').lower()   
43         self.clock_twelve = 'm' in to_unicode(xbmc.getInfoLabel('System.Time')).lower()
44         self.launch_popup(episode, playlist_item)                               
```

am going to try yours.  We will see.

**Comment by dagwieers** [comment]
You need to restart your Kodi, or disable/enable Up Next, otherwise the old code will keep on running and your modifications are not being used.

**Comment by Thunderbird2086** [comment]
@dagwieers, you're right.  It works like charm 😃

**Comment by dagwieers** [comment]
I wouldn't say *charm* though ;-) It is not performing what we would expect.
I have a second implementation that uses global setting `locale.use24hourclock`, but I think we need to fix it differently still.

**Comment by Thunderbird2086** [comment]
Thanks, @dagwieers!  Your PR #107 looks perfect to me 👍

**Comment by dagwieers** [comment]
@Thunderbird2086 Can you try PR #107 again? We are now using the string format coming straight from Kodi.
