### ISSUE TITLE
Suggestion:  single string for "Up Next in" for notification

### ISSUE THREAD

**Issue by Thunderbird2086** [im85288/service.upnext#108]
As ["Up Next in"](https://github.com/im85288/service.upnext/blob/16625400ec961add172428d6fabde91373bc064d/resources/skins/default/1080i/script-upnext-upnext.xml#L100) is declared in msgctxt `#30008` and `#30036` separately, it's hard to add translation for Japanese. 

For Japanese, the translation becomes as below. 
```
次のエピソードの再生までsss秒

   where sss is seconds
```
As there's no space in Japanese,  the separated `in`(#30036) cannot be translated properly.

**Comment by dagwieers** [comment]
I am going to modify those strings into pyformatted strings (https://pyformat.info/) so you have all the flexibility. It was on my todo list, but no pressing need.

I will do it in the next hours.

**Comment by dagwieers** [comment]
Looking into this, it is not that simple. The strings are used in the skin as separate string:

```xml
<label>$ADDON[service.upnext 30008] $ADDON[service.upnext 30036] [COLOR FFFF4081]$INFO[Player.TimeRemaining(ss),,][/COLOR] $ADDON[service.upnext 30035]</label>
```

So if I would make a single string like:

    Up Next in [COLOR FFFF4081]{remaining}[/COLOR] seconds

which in Japanese would become:

    次のエピソードの再生まで[COLOR FFFF4081]{remaining}[/COLOR]秒

I need to rewrite that `remaining` myself from a loop. Let me investigate how others do this in their add-ons.

**Comment by dagwieers** [comment]
The solution is much more simple than I expected:

    Up Next in [COLOR FFFF4081]$INFO[Player.TimeRemaining(ss),,][/COLOR] seconds

and in Japanese:

    次のエピソードの再生まで[COLOR FFFF4081]$INFO[Player.TimeRemaining(ss),,][/COLOR]秒

Not as pretty, but as effective. Expect a new PR.

**Comment by dagwieers** [comment]
So this is ready to be reviewed and merged.
