### ISSUE TITLE
Translate UpNext to as many languages possible

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#112]
With the upcoming v1.1.0 release including new settings and a new developer mode, it is time to look at the languages supported by the add-ons using UpNext, and reach out to their translators to translate UpNext and related add-ons to their language.

~The first goals is to prepare v1.1.0 and make changes that may influence translation files.
(e.g. restructure strings, add needed functionality, etc.) Then we can ask new and existing translators to help out with this task.~

I prepared a list of languages supported by **Netflix**, **inputstreamhelper** and **inputstream.adaptive**, which is available in the Wiki:
https://github.com/im85288/service.upnext/wiki/Translations

**Comment by sagatxxx** [comment]
how can i help to spanish translate?

**Comment by dagwieers** [comment]
@sagatxxx Create a translated .po file for the Spanish (es_es) language based on the English (en_gb) version.

**Comment by dagwieers** [comment]
### Existing language
We have the following issues for existing languages (run `make language` in the master branch):
- **Japanese** (ja_jp): Syntax errors  --  *@Thunderbird2086*
- **French** (fr_fr): 18 fatal errors  --  *@zecakeh*
- **German** (de_de): 1 fatal error  --  *@tweimer*
- **Croatian** (hr_hr): 22 fatal errors  --  *@arvvoid*
- **Italian** (it_it): 1 fatal error  --  *@EffeF*
- **Korean** (ko_kr): 3 fatal errors  --  *@Thunderbird2086*
- **Polish** (pl_pl): 1 fatal error  --  *@notoco*
- **Hungarian** (hu_hu): 4 fatal errors  --  *@frodo19*

**Comment by dagwieers** [comment]
### New language
We would like to offer translations for every language that is supported by related/consuming add-ons (like Netflix) for the best experience by users:
- **Czech** (cs_cz): @angelblue05 @DJSweder @svetlemodry
- **Danish** (da_dk): @coz2001
- **Greek** (el_gr): @Twilight0
- **Spanish** (es_es): @sagatxxx @roliverosc @boblo1 @Alfredo-Martinez @danielchc
- **Finish** (fi_fi): @Lam4hound 
- **Hebrew** (he_il): @Eng2Heb
- **Lithianian** (lt_lt): @egidijusm @tigriso1
- **Latvian** (lv_lv): @marcisbe
- **Brazilian** (pt_br): @Wanilton @MediaBrasil
- **Portuguese** (pt_pt): @beatwiz
- **Russian** (ru_ru): @vlmaksime
- **Slovak** (sk_sk): @matejmosko
- **Swedish** (sv_se): @emilsvennesson @Sopor

We plan to release by Wednesday, but any translations we get after Wednesday will go into the next release. Thanks in advance!

**Comment by mediabrasiltv** [comment]
@dagwieers, translation pt-br done, opened PR.
Regards,

Wanilton

**Comment by Twilight0** [comment]
Cheers, have fun: https://github.com/im85288/service.upnext/pull/157

**Comment by sagatxxx** [comment]
@dagwieers Done spanish translation, how can I upload it?

**Comment by dagwieers** [comment]
@sagatxxx The best option is to fork (on GitHub) and clone our repository, then make a branch, add the file to your branch, make a commit and push it to your GitHub fork. Then make a pull request from this branch.

But you can also make the changes in GitHub by adding the file in the correct place, and the GitHub web-interface will help you make the PR.
- Start from here: https://github.com/im85288/service.upnext/new/master/resources/language/resource.language.es_es/
- Fill in **strings.po** as filename
- Then copy your content
- At the bottom give a commit-message

**Comment by sagatxxx** [comment]
> @sagatxxx The best option is to fork (on GitHub) and clone our repository, then make a branch, add the file to your branch, make a commit and push it to your GitHub fork. Then make a pull request from this branch. _(Steep learning curve)_
> 
> But you can also make the changes in GitHub by adding the file in the correct place, and the GitHub web-interface will help you make the PR. _(Anyone can do this)_
> 
> * Start from [resources/language/resource.language.es_es/strings.po](https://github.com/im85288/service.upnext/new/master/resources/language/?filename=resource.language.es_es/strings.po)
> * Then copy your _strings.po_ content (we don't need the other files)
> * At the bottom give a commit-message
> * Then follow the instructions
> 
> Alternatively, I can do it for you.

I think it's done

**Comment by dagwieers** [comment]
> I think it's done, i'm a little newbie

There is no pull request in this project. But I noticed you made a pull request in your own project.

**Comment by sagatxxx** [comment]
Within my ignorance I think I have renamed the folder, now I am lost on how to continue

**Comment by im85288** [comment]
Don’t worry about it, it has now been included and will go into the next release. Thanks for your contribution

**Comment by sagatxxx** [comment]
ohh..., fine!! thanks

**Comment by matejmosko** [comment]
Slovak done.

Thanks for your work
*Matej Moško*
zabávam ľudí v kluboch (Turban Quiz <https://turban.panakrala.sk/>,
Bratislavský
Kaviár <https://bratislavskykaviar.sk/>, Hry Pána Kráľa
<https://www.facebook.com/PanaKrala.sk>)
píšem o divadle (Monitoring divadiel
<https://www.monitoringdivadiel.sk/recenzenti-a-recenzentky/recenzent/matej-mosko/>,
MLOKi <https://www.mloki.sk/user/matej-mo%C5%A1ko>)
píšem aj pre televízor (kamosko.panakrala.sk)

**Comment by dagwieers** [comment]
@matejmosko Found it in your GitHub fork and made a PR from it #163 :+1:

**Comment by dagwieers** [comment]
If you were considering to translate Up Next, we are going to delay releasing v1.1.0 to Thursday evening, probably 18:00 CEST. This should give you one extra day to contribute your translations!
Any translations we get after that cut-off point will go into the next release.

Thanks to all translators we already have **9 new languages in the upcoming release**. More than we could have hoped for! :+1:

**Comment by dagwieers** [comment]
Thanks everyone ! We released version v1.1.0 so I am going to close this issue.
For the next release we will call out to translators again (for incomplete languages).
But feel free to send your translations as soon as you find the time.

**Comment by dagwieers** [comment]
We have created translator-teams in the @Kodi-addons organization at: https://github.com/orgs/kodi-addons/teams/translators

This will help us translate Kodi add-ons to more languages in the future using less effort.
If you are willing to help out, join a language team!

**Comment by dagwieers** [comment]
We now have a special request for translating Up Next in the Add-ons project at: https://github.com/add-ons/translations/issues/4

**Comment by olavinto** [comment]
I just have to ask: Why isn't the Kodi Weblate utilized for by many addons for translations? It is so much more accessible to translators and would offer string by string management, glossaries and TMs which would help with terminology and consistency a lot. Doing it via GitHub by simply editing files directly seems super time consuming, not to mention making it completely inaccessible to many potential translators.

I do a lot of Finnish translating and proofreading especially at Crowdin and Weblate and there are many addons (like this one) that I use and have used for years and would happily translate. But doing it without any real translation workflow support features seems super counterproductive to me, and can easily lead to a situation where terminology in a single Kodi instance is all over the place if consistency isn't manually checked against the current Kodi translation.

**Comment by MoojMidge** [comment]
The effort to translate this addon predates the Kodi migration to Weblate by at least 1.5 years (probably more actually).

Utilising Weblate requires some administrative work and changes in the addon workflow process, so while it seems like a good idea, it needs a bit of effort to achieve and at the moment there is no one to do this.

**Comment by olavinto** [comment]
How is this Transifex project related to this one?:
https://www.transifex.com/emby/up-next/
