### ISSUE TITLE
Not advancing to next episode

### ISSUE THREAD

**Issue by jgslade** [im85288/service.upnext#117]
At the end of an episode instead of going to the next one it is now staying on the last frame and the timer keeps going. 

I am running on libreelec 9.2 with Kodi 18.5. I have rebooted the system, powered down the system, and uninstalled up next both with and without deleting the settings.

**Comment by im85288** [comment]
Please see: https://github.com/im85288/service.upnext/wiki/Report-a-Bug for how to report a bug with the info we need to try and resolve it

**Comment by dagwieers** [comment]
@im85288 We can make this easier by adding an issue-template in GitHub with the instructions and the information we expect.

I will make a proposal.

**Comment by notoco** [comment]
Sometimes I wonder if you're even sleeping...

**Comment by jgslade** [comment]
https://paste.kodi.tv/abizirojaw.kodi

UpNext is version 1.0.7
Libreelec has the latest updates installed.

When the log was taken the show was at minute 24 of about 21.

I enabled debug on the UpNext addon settings, do I need to change any Kodi settings to get a more meaningful log?

**Comment by im85288** [comment]
No the logs have all the info we need...however it seems to say everything worked correctly. Let’s see if @dagwieers has any ideas

**Comment by dagwieers** [comment]
I don't see a good reason why it would have failed for local media. I explicitly tested this user scenario before the v1.0.7 release, and I just tested it again with the v1.0.7 release and it works fine for me. I don't know what else to try to debug this.

(Tested on LibreELEC v9.2 on Raspberry Pi)

**Comment by dagwieers** [comment]
One thing you could maybe try is to enable debug logging in Kodi.
Maybe the issue is in Kodi itself?

And you could try and reproduce it using a previous version of Up Next (like v1.0.1).

**Comment by jgslade** [comment]
The media is an NFS share.

Here is a link to the log after enabling logging in kodi:
http://ix.io/23DP

I just tried it with 1.0.1 and it worked. Here is the log from it working:
https://paste.kodi.tv/yudacewifa.kodi

**Comment by dagwieers** [comment]
> The media is an NFS share.

My media as well.

**Comment by dagwieers** [comment]
I am sorry, I can't tell anything from the v1.0.7 logs. It appears to play it correctly, and the Kodi logging is simply too verbose and doesn't give me any obvious clues.

The v1.0.1 logs don't log anything coming from the add-on, so not sure what is going on there.

**Comment by jgslade** [comment]
> My media as well.

Drat

Sorry, forgot to enable logging on 1.0.1.
Here's a good log, hopefully:
http://ix.io/23EJ

**Comment by dagwieers** [comment]
It must be related to changes in **monitor.py** or **player.py**. In order to debug this, I would have to add more logging to the functions that shortcut it working (preemptive returns). It would have been easier if I could reproduce it myself  :disappointed:

**Comment by dagwieers** [comment]
What's more, I happen to have the same season and episodes of the Big Bang Theory and I tried to reproduce it with the exact episodes (S6E10 -> S6E11) and it works for me. I played all episodes from S6E08 up to S06E13 in succession and it behaved as expected (with the master branch).

This is tested with the master branch and LibreELEC 9.2.0 (Kodi 18.5) on RPi 3B.

**Comment by dagwieers** [comment]
Tried it as well with v1.0.7 and no issues encountered :disappointed:

**Comment by jgslade** [comment]
If it helps I tried each of the releases between 1.0.1 and 1.0.7. It would advance to the next episode with each of the releases, but the pop isn't displayed. I then reinstalled 1.0.7 and it started behaving like 1.0.2-1.0.6 where it advanced, but didn't show the popup, it also didn't stop advancing after 3 episodes, it just kept playing.

I have reinstalled 1.0.1 and it is working properly.

>This is tested with the master branch and LibreELEC 9.2.0 (Kodi 18.5) on RPi 3B.

Same system I have, such a baffling issue.

**Comment by dagwieers** [comment]
@jgslade This is quite useful! So it did work in v1.0.1, but no longer on v1.0.2?

That would make the culprit inside this changelog: https://github.com/im85288/service.upnext/compare/1.0.1..1.0.2

I will investigate this evening if I see something suspicious that could explain this behaviour.

**Comment by dagwieers** [comment]
To summarize, the only changes relate to #46 and includes:
- JSONRPC abstraction (low impact)
- Playlist handling (high impact)
- Add endtime property (low impact)

But I will check this code to understand what it does.

@angelblue05 You were involved with these changes, maybe you can pinpoint the reported issue to a specific change? Thanks!

**Comment by angelblue05** [comment]
Maybe the playlist implementation, but that wouldn’t interfere with the pop up.

Please share your upnext settings.

Does the popup work the first time, then stops working?

**Comment by dagwieers** [comment]
According to the logs it appears to work correctly?

**Comment by Dnkhatri** [comment]
@jgslade are you using @notoco version of audio profiles I think that is what causing the problem. Updating to his version made the upnext stop working removing it fixed it for me.

**Comment by notoco** [comment]
@Dnkhatri Strange, I use both on different systems and it works everywhere. audio.profiles has nothing to do with playback. Only change audio parameters with json. Does not affect playback, rewinding

**Comment by notoco** [comment]
And until last week in my repo there were git versions of the upnext add-on and it could be a problem in them. Currently they are gone, they are moved to a completely private separate repository.

**Comment by Dnkhatri** [comment]
> And until last week in my repo there were git versions of the upnext add-on and it could be a problem in them. Currently they are gone, they are moved to a completely private separate repository.

Weird I will check again when I have the time later I just updated to your version of audio profiles and upnext stopped working. Audio profiles stopped showing the selection dialogs as well so I went back to the kodi repo audio profiles and upnext started working again.

**Comment by notoco** [comment]
Go to my repo and open issue

**Comment by jgslade** [comment]
>Please share your upnext settings.
They are at the default settings

>Does the popup work the first time, then stops working?
With the not advancing the popup shows up does the count down, but then it doesn't advance. With the continuous play the popup never shows up.

I figured it out. I uninstalled Up Next and it still continued to auto play, so I checked the kodi player settings and it was configured to auto play the next episode. I turned that setting off, reinstalled Up Next and it behaved properly. 

There must be some conflict with the way Up Next works and the kodi auto play.

Thank you for the help.

**Comment by dagwieers** [comment]
> I figured it out. I uninstalled Up Next and it still continued to auto play, so I checked the kodi player settings and it was configured to auto play the next episode. I turned that setting off, reinstalled Up Next and it behaved properly.

In that case we should warn the user for this Kodi setting and either work around it, or not function at all (for local content) when set.

**Comment by angelblue05** [comment]
Have you replicated this issue yourself? Works fine for me either way. Must be a race condition causing this.

**Comment by dagwieers** [comment]
@angelblue05 I could not reproduce this either. Not even using the same device, platform, add-ons and media. I don't see how both could interfere when the pop-ups clearly happen before the video ends (and they are not shown) whereas automatically playing is something that only occurs at the end of a video.

I also don't get that we don't see pop-ups, whereas the logs clearly indicate the right codepaths have been triggered. As if the logs do not agree with the experience.

Not getting any pop-ups could be related to the service not running (crashed, stopped, disabled). But this would not explain why it works on v1.0.1, and not anything newer.

Also not sure how we could improve the add-on to get better reporting or easier troubleshooting afterwards.

That said, **Play next video automatically** being set for **Episodes** is quite confusing as it would continue playing the next episode even when the user decided to Close the pop-up or has Up Next configured to not continue playing when no action was taken.

So I still think this is something we have to fix. Either by reporting to the user this conflict between the Kodi settings and the Up Next add-on, or to force disabling this Kodi setting (usually frowned upon, but in this case there's a direct relation to Up Next's purpose).
