### ISSUE TITLE
Support for a plugin URL as play info

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#132]
I think we can simplify how the add-on integrates with UpNext.

Currently it uses notifications,
- one coming from the add-on for informing UpNext about a potentially upcoming episode for the currently playing video, and
- one from UpNext to ask the add-on to play the next episode, when that time has come

For the second notification it requires the add-on to have a service thread that waits for this notification and acts on it. This is complexity that should not be needed. In fact, requiring add-ons to have their own service is (in the larger picture) unwanted.

We could also support a mechanism that lets UpNext initiate the next episode itself. Let's call this `play_url` and it would contain e.g. `plugin://plugin.video.vrt.nu/play/upnext/vid-57e751d2-e744-4b33-ade6-b33ea3e1bba5` so that the add-on does not need any service running.

This would make integrating with UpNext a lot easier for most add-ons as they only need to perform a single notification.

**Comment by dagwieers** [comment]
An implementation like this would be mutual exclusive with `play_info` and if both are provided, only one will be acted on.

**Comment by im85288** [comment]
The reason it works as it does currently is to allow any integrating addon to decide exactly how they want to play the item. There can be for example a scenario where the integrating addon needs to do some internal logic prior/after receiving notification to play the item.

If I understand correctly your proposal is for an alternative way of handling the playback which could simplify integration, I'm not against that as long as we support both methods to allow for addons with more complicated requirements.

**Comment by dagwieers** [comment]
@im85288 Since the call to play is also handled by the add-on, it still has all the flexibility to do as it pleases. Just as clicking any ListItem in a directory listing, or starting a Favourites item. In fact our add-on simply calls `Player.Open` on receiving the signal. So I expect this to be a bit more efficient.

I have an implementation ready.
