### ISSUE TITLE
never get Still Watching dialog

### ISSUE THREAD

**Issue by anxdpanic** [im85288/service.upnext#135]
`played in a row` always seems to be `1`

Log: https://drive.google.com/file/d/1Xm9Irrt8ZsXIeWDDTnFAoMR6QDOltcvr/view
Implementation: https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/master/resources/lib/composite_addon/addon/up_next.py
https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/master/resources/lib/composite_addon/addon/monitor.py

I'm probably missing something obvious.

**Comment by dagwieers** [comment]
I have to say that the code related to this is quite hard to read.

**Comment by anxdpanic** [comment]
upnext_data: https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/51cee45f1d32ed13b74836ec917f5c99fe157658/resources/lib/composite_addon/addon/up_next.py#L109
episodes: https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/51cee45f1d32ed13b74836ec917f5c99fe157658/resources/lib/composite_addon/addon/up_next.py#L134

jsonrpc player.open on _play_action

**Comment by dagwieers** [comment]
I would like to release v1.1.1 next week, ideally with a fix for this. Do we have an understanding of what is going wrong here?

**Comment by anxdpanic** [comment]
I don't, sorry. I haven't had enough time recently, and in the next couple weeks I will probably have few opportunities to look into it, but I will try. I have had no reports of this issue either, so it seems to be only me affected. I would be alright with this being closed until I'm able to provide more information.

**Comment by dagwieers** [comment]
I am not sure if this functionality is something a lot of people would notice of it would be broken.

**Comment by im85288** [comment]
True a hard one to spot, there used to be settings (hopefully still there but not checked for a while) to configure how many episodes must be watched without user interaction for it to occur. When I get time I’ll look to replicate locally to test it out

**Comment by dagwieers** [comment]
It would be nice to get to the bottom of this before we are releasing v1.1.1.

**Comment by anxdpanic** [comment]
@dagwieers 
Is there any where in the code in particular you suspect or where you would suggest to start looking?
Hopefully have some time in the near future to look at it.

**Comment by anxdpanic** [comment]
I took a short look at this, I'm not sure it will make v1.1.1

https://github.com/im85288/service.upnext/blob/7985d4f7ee14c42920dcb98db6e501df64a9567e/resources/lib/playitem.py#L38

self.state.current_tv_show_id is always None in my case

**Comment by im85288** [comment]
@anxdpanic Are you providing the tv show ID in the data sent to the addon as described here: https://github.com/im85288/service.upnext/wiki/Integration under the next_info section?

That’s all I can think may be causing an issue. Make sure not to send None. It can be anything as long as it remains consistent for that TV show.

So for example if it’s the simpsons sending a TV show ID of ‘thesimpsons’ will do...or whatever is easiest from your side

**Comment by anxdpanic** [comment]
It's set, and if not available set to `-1` instead of `None` . In my testing tvshowid was/is always provided

https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/c38c3c4ba428af35ef3f8c315bee49dbc54ef0ad/resources/lib/composite_addon/addon/up_next.py#L202

I've also tried the id's as str and using `Watch Now` as well as letting it play through.

**Comment by im85288** [comment]
Hmm..If you enable logging as stated on the Wiki are you seeing a non None value for the tvshowid in the  log: `handle_addon_lookup_of_current episode returning data  `

**Comment by anxdpanic** [comment]
This is the notification sent and received, https://pastebin.com/U39LXKh4

**Comment by im85288** [comment]
Looks perfect..let’s see if @dagwieers has any ideas.

We may need to add more logging if we still cannot get to the bottom of it.

**Comment by anxdpanic** [comment]
Okay, I'm going to close this out. All my installs and portables now work and I can't reproduce it anymore. I can't think of anything I've changed that would cause it, but hopefully that's all it was.
I'll re-open if I experience it again.
