### ISSUE TITLE
New feature request for known credit start time

### ISSUE THREAD

**Issue by CastagnaIT** [im85288/service.upnext#136]
In Netflix addon i have the possibility to know the exact position time where the final credits begin
i have a value in integer timestamp in seconds
(but if you prefer i can covert in other formats)

what i have in mind is having the possibility to add a parameter to override the estimated time to show the UpNext window, with the exactly time provided from netflix

param example:
{'credits_starts_at': 5821}
So at 01:37:01 (timestamp converted) the upnext window is shown

I have never considered this possibility.. but before officially include it i should have the possibility to do some tests, to make sure that the netflix credits time value is acceptable

let them know what you think

**Comment by dagwieers** [comment]
This is already possible by using `notification_time`. This will override our heuristics or default time.

**Comment by CastagnaIT** [comment]
oh thank you i did not see, i will do some test

**Comment by CastagnaIT** [comment]
there was already implemented but i did not know was for that purpose...

**Comment by dagwieers** [comment]
Right, it always worked correctly in Netflix so I was surprised by your request :wink: 
AFAICT Netflix is the only add-on that has access to this information today.

**Comment by im85288** [comment]
Yes indeed, it was implemented specifically for the Netflix addon...hopefully one day we can use it with other addons when the data around them improve
