### ISSUE TITLE
Extend the time before the notification

### ISSUE THREAD

**Issue by notoco** [im85288/service.upnext#14]
Is it possible to extend the time before which the notification will appear, eg 5 minutes before the end? Many Netflix series have a fairly extensive payroll list and kids have to wait long until UpNext appears

**Comment by im85288** [comment]
This works perfectly with the Netflix add on as the time for the notification is sent via that add on. Allowing the pop up to come up at any time. You may need to install the new beta version from @caphm to pick up the integration though

**Comment by notoco** [comment]
I'll check it out later in the house, but it seems to me that despite using the Netflix version of 14.x beta, it still displays 2 minutes before the end. At least using the episodes imported to the library. But I'll check later.
