### ISSUE TITLE
No me funciona con el  Skin Aeon Nox de Silvio

### ISSUE THREAD

**Issue by alexfrancoc17** [im85288/service.upnext#141]
Estimados: 
me place saludarles, al tiempo de agradecerle de disponer de UpNext para usar en las series.

No me esta funcionando en el Skin de Aeon Nox de Silvio; y usando el Addon Alfa de contenido de series.

link del log: https://paste.kodi.tv/ekegifazoj.kodi

Me puedes ayudar, muchas gracias.

saludos

AF

**Comment by dagwieers** [comment]
@im85288 Maybe you know what is going on here. Control 3014 is the progress bar, so I assume in the past skins did not require a progress bar control, but they do now?

**Comment by dagwieers** [comment]
Ah, this is related to #142

**Comment by alexfrancoc17** [comment]
Muchas gracias @dagwieers , estube viendo el 142, pero no soy muy experto, por lo que entendí hay que modificar una parte del código en "resources/lib/playbackmanager.py" del addon upnext, muchas gracias, vere si el 142 me ayuda, y les comento
