### ISSUE TITLE
Window.Property(endtime) wrong

### ISSUE THREAD

**Issue by sualfred** [im85288/service.upnext#169]
Just noticed it a few time that Window.Property(endtime) is populated wrong

Example:
Correct -> 21:15 
Window.Property(endtime) -> 2121:15

It looks like the hours are duplicated (hh+hh+ss)

**Comment by dagwieers** [comment]
That is interesting as I haven't seen this myself. Can you send me a debug log so we can compare what data is provided?

**Comment by sualfred** [comment]
I cannot reproduce it on the PC, but I keep getting in randomly on my Nvidia Shield (24h date format).

**Comment by dagwieers** [comment]
I would still need a debug log to understand where the issue lies.
Maybe you could share in which add-on you see this? Or is this with local media?

**Comment by sualfred** [comment]
Emby for Kodi with native paths -> Local media.
I have wait until my Shield is free to reproduce it.

**Comment by dagwieers** [comment]
I have not been able to reproduce it using Kodi and local files.

**Comment by sualfred** [comment]
It's hard to find a time frame to reproduce it on my Shield. Family is
blocking all the time. And I'm quite busy atm with work. I will ping you
once I was able to test it there


Dag Wieers <notifications@github.com> schrieb am Di., 4. Feb. 2020, 11:32:
