### ISSUE TITLE
OSMC (Leia) - Audio delay and only playing one item

### ISSUE THREAD

**Issue by danmed** [im85288/service.upnext#17]
i didnt turn debugging on until about 18:00 so this log contains the issue both with and without debugging on..

https://paste.kodi.tv/upekiteyun.kodi

I have this issue on both LibreElec and OSMC (both Leia)

It will play 1 extra episode, but not a 2nd.. Equally in OSMC, the audio plays for 10 seconds whilst the video is frozen, then the video plays with no audio until the sync up.. This doesn't happen on LibreElec.

The other issue is that this does not work at all with Smart Playlists.. it finds the next episode and counts down, but it never plays it (This is not in the debug log.. but hopefully you'll know what's up)..

This is running off a MySQL DB btw.

**Comment by danmed** [comment]
OK, i think i've fixed this with a fresh install of OSMC.. the audio delay problem is there but i don't think thats your problem as it's not present in LibreElec.

**Comment by angelblue05** [comment]
@danmed 
I know it's been a little while, but is your issue resolved with UpNext version 1.0.1?

**Comment by danmed** [comment]
I'm afraid I havn't used it since.. I just set Kodi to auto play the next
episode until I tell it to stop.

**Comment by angelblue05** [comment]
Ok thanks for replying back. Well if you want to give it another try someday. I am fairly certain this has been resolved.
