### ISSUE TITLE
Up Next Notification Message 

### ISSUE THREAD

**Issue by weebl101** [im85288/service.upnext#173]
Hello, 

When using the newest version of UP Next the notification that appears at the end of a episode is bugged. 

It says:

Up Next Up Next in 12 seconds 12 Continue watching in 12 Seconds... 

Screenshot attached. Let me know if you need logs and I will enable debug. 

Thanks in advance. 
![image](https://user-images.githubusercontent.com/7332213/74714330-162eb600-5276-11ea-8c30-a9f96196128d.jpg)

**Comment by im85288** [comment]
Thanks for the report...that looks crazy!

Is that reproducible? If so can you please attach a debug log and indicate which Skin you are using so we can rule out it being a skin issue.

**Comment by weebl101** [comment]
I have it on both my setups. I am using Arctic Zephyr 2. 

All previous versions of the app work correctly, it’s just the latest. I will run a couple episodes and attach a debug log.

Thanks for the quick reply.

**Comment by weebl101** [comment]
Stupid question, where does the add on save the logs?

**Comment by im85288** [comment]
No problem if you follow the link here: https://github.com/im85288/service.upnext/wiki/Report-a-Bug
It should give you enough info for getting the logs

**Comment by weebl101** [comment]
https://drive.google.com/open?id=1C5_i7HyMTEacmNs3GSStVK68PWr8VVvm

hopefully this helps

Thanks again

**Comment by notoco** [comment]
This is a problem with the AZ2 skin - download the git version - this bug has already been corrected: https://github.com/jurialmunkey/skin.arctic.zephyr.2

**Comment by weebl101** [comment]
It must have popped back up, I am currently running 0.9.58 alpha1 - the guy is older. I will log it with the developer of the skin. Thanks so much for your help :-)
