### ISSUE TITLE
Error "AttributeError: 'NoneType' object has no attribute 'update'"

### ISSUE THREAD

**Issue by CastagnaIT** [im85288/service.upnext#176]
I don't know if you've already fixed it

but while i was testing with netflix, i noticed this:

<pre>
2020-02-29 10:25:32.695 T:17428   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'update'
                                            Traceback (most recent call last):
                                              File "C:\Users\gotta\AppData\Roaming\Kodi\addons\service.upnext\resources\lib\monitor.py", line 90, in onNotification
                                                data.update(id='%s_play_action' % sender.replace('.SIGNAL', ''))
                                            AttributeError: 'NoneType' object has no attribute 'update'
                                            -->End of Python script error report<--
</pre>

line 4379
log: https://paste.kodi.tv/

On Windows
latest Kodi 19

**Comment by dagwieers** [comment]
So it appears Up Next received data which can not correctly be parsed as JSON. I would need to reproduce this to improve the logging/reporting of such issues.

Can you tell me what version of Netflix add-on, and what video, season and episode this happened with? (There is no log, just a URL if a pastebin service)

**Comment by dagwieers** [comment]
I would like to get this fixed (or at least logged better) in the v1.1.1 release planned for next week.

**Comment by CastagnaIT** [comment]
Unfortunately, I was doing dozens of tests, so i don't remember the situation

I'm gonna have to run some more tests these days, so if i find out that it's still happening,
I'll try to give you more information

**Comment by CastagnaIT** [comment]
keeps on happening:
another example: https://github.com/CastagnaIT/plugin.video.netflix/issues/604

I suspect that this method read incoming and also outgoing messages
https://github.com/im85288/service.upnext/blob/master/resources/lib/monitor.py#L84

**Comment by dagwieers** [comment]
Up Next does not send out messages with methods including **upnext_data**. So everything it handles are incoming messages.

**Comment by CastagnaIT** [comment]
I wrote only a tip because some time ago using the monitor i noticed that it intercepts both way
however the error persists

**Comment by dagwieers** [comment]
I merged the troubleshooting improvements for this case, so if you see this reported, it would be nice if they can try out the master branch if they can reproduce this.

**Comment by CastagnaIT** [comment]
i will update my desk
it's possible that in the future tests i may be able to catch him

**Comment by CastagnaIT** [comment]
Now i think i have found the problem
when i watch a movie instead of an episode
nf addon send a signal to upnext by sending `None` as data
this was unhandled by upnext would break with a wrong data

I will prevent the call when the data is empty

**Comment by CastagnaIT** [comment]
now that this case is handled, closing the issue

**Comment by dagwieers** [comment]
Yes, Up Next only makes sense for series, not for movies. Thanks for reporting back. Improved logging like this is paramount.
