### ISSUE TITLE
Incorrect Ends at: time displayed during Up Next episode countdown

### ISSUE THREAD

**Issue by boredazfcuk** [im85288/service.upnext#182]
Just a cosmetic thing really, but I noticed that the `Ends at:` time is displayed incorrectly if the end time crosses into the next day.

For example, if it was 23:34, and the show was an hour long, the time in the top right corner would display as:
```
        23:34
Ends at:  :34
```
When it should really be displayed as
```
        23:34
Ends at: 0:34
```

Thanks

**Comment by dagwieers** [comment]
This should already have been fixed in the master branch, but has not been released yet.
Can you verify this on the master branch? Thanks.
