### ISSUE TITLE
Python 3 version for Kodi Matrix

### ISSUE THREAD

**Issue by Razzeee** [im85288/service.upnext#189]
Hey there,

just curious if your working on it or want any help.

Cheers

**Comment by im85288** [comment]
Hi @Razzeee, it should just work (that's the theory...as when creating it it was supposed to be python3 and python 2 compatible!)

Anyway I have not tested it, but just created a Matrix branch along with a v2.0.0 matrix release. Please give it a shot and yes always happy for PRs if you find anything needs to be fixed.

Cheers

**Comment by Razzeee** [comment]
If that's true then you just need to submit it. There is a submit script, that I can setup if you are interested

**Comment by im85288** [comment]
Well it needs tested first to confirm that theory! I just changed the python dependency to 3.0.0 in the new branch. Once we confirm it’s working, sure I’ll submit it then.

**Comment by dagwieers** [comment]
In version X.Y.Z we tend to use X for major updates, Y for new features and Z for bug fixes.
We have had support Python 3 for a long time now.

So I don't think we needed a new major release for this.

**Comment by im85288** [comment]
Cool, I’m away from my laptop at the moment but feel free if you get the chance to change it back to 1 as the major release.

On a related note should we just go full steam matrix on master? i.e change the python version to 3 in addon.xml

**Comment by dagwieers** [comment]
@im85288 I don't think the mast branch should be Matrix. As most (if not all) users are running Leia and it is easier if people can install a fix by downloading the branch ZIP file.

It is unfortunate that the Kodi devs decided to make it impossible to have a single ZIP file that can work on both Matrix and older Kodi releases (as a lot of developers have made their add-ons work on both Python 2 and Python 3). Creating a hurdle for no real gain IMO...

Once Matrix is released and the majority of users is running Matrix we can switch the master branch over to Matrix.

**Comment by im85288** [comment]
@dagwieers no worries, we can just keep the matrix branch until leia bites the dust. 

@Razzeee I will get a version submitted to the matrix repo. If you do have the submit script at hand that would be useful.

**Comment by dagwieers** [comment]
@im85288 IMO We don't need 2 branches, it is the same code, we don't want to maintain 2 branches with the same code.

For inputstreamhelper we have a GitHub CI workflow that creates a Matrix ZIP in the releases, and also submits a separate Matrix package from the master branch

**Comment by im85288** [comment]
@dagwieers I agree, I’ll remove it tomorrow.

**Comment by dagwieers** [comment]
I will backport the changes to make a Matrix release and add the GitHub CI workflow from @mediaminister. We can then make a new release with the latest fixes for both Leia and Matrix. Long overdue!

**Comment by im85288** [comment]
@dagwieers cool thanks for taking care of it.

**Comment by dagwieers** [comment]
@im85288 If you have added the required secrets (included the personal GH_TOKEN) you can tag v1.1.1 and push it to GitHub. This should set off the release workflow that (if all is well) will create a new release in GitHub and creates the PRs to the Kodi repository for Leia and Matrix.

**Comment by Razzeee** [comment]
I'm not sure what your release script is trying to do, but it seems way more complicated then the one I've been using that's documented here https://github.com/xbmc/action-kodi-addon-submitter

**Comment by dagwieers** [comment]
We are using it, so I guess we are doing alright.

**Comment by Razzeee** [comment]
Sure, if your up to handle the added complexity it should be fine. Just saying that there is a streamlined pipeline.

**Comment by dagwieers** [comment]
@Razzeee You still need to have the released ZIP files for Leia *and* Matrix, and your streamlined pipeline does not create those ZIP files (modifying the addon.xml etc.). So that is the added complexity. Not our preferred way to handle this, we would have liked a single ZIP file for all releases as it worked before.

**Comment by Razzeee** [comment]
I get why you would want that, but that's way out of context here and I also don't agree, that it was like that before. But that might have been due to how I handled my addons to get the most out of the new apis.

**Comment by dagwieers** [comment]
@Razzeee You lost me there. Before the change in Matrix, all our add-ons (including this one) would work out-of-the-box on Leia *and* Matrix. And we had quite some users running Matrix. I think most of them went back to Leia because suddenly no add-ons were available anymore.

Our release pipeline creates two ZIP files (one for Leia and one for Matrix) according the new rules that require a single fix in addon.xml. Then creates a release with these two files added, and then calls your GitHub CI action. Feel free to suggest how to make this less complicated. I think every step in that pipeline is pretty much required. It may not be pretty, but that's beyond our control...

**Comment by dagwieers** [comment]
BTW @mediaminister proposed an alternative solution that didn't require this breakage, but it was rejected. https://github.com/xbmc/xbmc/pull/17435

**Comment by Razzeee** [comment]
AFAIK the GitHub CI action does the addon.xml changes for each branch it needs to send to the repo. But I guess for you it's about creating matching ZIP files? I don't think that anyone has worked on that. I'm not even convinced of the value, but might be valid.

**Comment by dagwieers** [comment]
Well, we have releases been sitting in the Kodi repo queue waiting to be accepted for days, so it helps if our users can already update when that is a necessity even when a fix is not yet distributed. Including a Matrix release.

So this is quite useful: https://github.com/add-ons/plugin.video.vrt.nu/releases

**Comment by mediaminister** [comment]
This workflow I originally wrote for InputStreamHelper predates [April 9](https://github.com/xbmc/action-kodi-addon-submitter/commit/01e470b96e5077ec824c94270f42ea1a3ca1c311).
I guess with the recent developments it's possible to simplify this workflow, but I didn't take the time yet to do this.

**Comment by im85288** [comment]
@dagwieers I added what should be the required secrets: EMAIL, GH_USERNAME and GH_TOKEN and just pushed tag v1.1.1 

As far as I can see nothing happened?

**Comment by dagwieers** [comment]
@im85288 The workflow does not seem to have triggered: https://github.com/im85288/service.upnext/actions?query=workflow%3ARelease

I cannot remember we had to enable something in the settings, but can you verify this:
https://github.com/im85288/service.upnext/settings/actions

I think **Enable local and third party Actions for this repository** should be enabled.

**Comment by im85288** [comment]
@dagwieers That was already enabled, I had not given it a proper GH_TOKEN (I made one up!), corrected that now with a proper personal token.

Is there a way to kick this off again, or do I need to bump to 1.1.2?

**Comment by dagwieers** [comment]
I noticed that a lot of the tags without 'v' have been restored, I removed them yesterday :-)
I think you can remove a tag, and then push it again. Let me test.
*(Although I don't think a missing secret prevents a workflow to be triggered)*

**Comment by im85288** [comment]
Sorry about that..my IDE for some reason committed 10 tags! I will leave it with you for now cheers

**Comment by dagwieers** [comment]
I removed the tag(s) and pushed v1.1.1 again and now it has triggered. So maybe it does check for the secrets :-)

**Comment by im85288** [comment]
It was an important secret! Cool checking

**Comment by dagwieers** [comment]
All credits go to @mediaminister, the release has the bits from the Changelog added, and there are now two downloads added, including the one for Matrix.

**Comment by im85288** [comment]
Cool stuff @mediaminister 

Worked like a charm: https://github.com/xbmc/repo-plugins/pull/2961#issuecomment-647519463
and https://github.com/xbmc/repo-plugins/pull/2962#issuecomment-647519906

Will close this issue now. Thanks all

**Comment by dagwieers** [comment]
@im85288 Maybe you can remove the tags without 'v' from your system as well?
```
$ git tag -d 0.1.0
$ git tag -d 0.1.1
...
```

**Comment by im85288** [comment]
@dagwieers sure I'll run those commands

**Comment by im85288** [comment]
@dagwieers I removed codecov.yml from the release as requested in the review:

https://github.com/xbmc/repo-plugins/pull/2961#issuecomment-647519463

Can you look at the one about the sleep statement?

**Comment by dagwieers** [comment]
@im85288 I don't really understand the problem, this is asynchronous so it should not be blocking anything AFAICT.

**Comment by im85288** [comment]
I think they don’t like sleep statements. I understand it can hang kodi if a shutdown is invoked and it’s in the midst of a sleep

**Comment by dagwieers** [comment]
The sleep is in fact an `xbmc.sleep()`, so I would have expected that this would be fine for a Kodi shutdown.

**Comment by im85288** [comment]
No idea really, let's see how they enen responds to your question. In the meantime I think we would need to change to use a Monitor to use the waitForAbort?

From memory I used to loop here didn't I, checking for a result before moving on rather than sleeping for 5 seconds

**Comment by dagwieers** [comment]
This sheds some light on the issue: https://forum.kodi.tv/showthread.php?tid=196360

You would expect `xbmc.sleep()` to be interruptible, rather than blocking for Abort requests.

**Comment by im85288** [comment]
So we can go for this in Player:

```
def onPlayBackStarted(self):  # pylint: disable=invalid-name
        """Will be called when kodi starts playing a file"""
        while not self.monitor.abortRequested():
            self.monitor.waitForAbort(5000)
            if not getCondVisibility('videoplayer.content(episodes)'):
                return
            self.state.track = True
```

**Comment by im85288** [comment]
Happy for me to commit that one?

**Comment by dagwieers** [comment]
The documentation actually states this: https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmc.html#gac81db027eab4f3b5bec4a7a5a1073e7e

> **Warning:** This is useful if you need to sleep for a small amount of time (milisecond range) somewhere in your addon logic. Please note that Kodi will attempt to stop any running scripts when signaled to exit and wait for a maximum of 5 seconds before trying to force stop your script. If your addon makes use of xbmc.sleep() incorrectly (long periods of time, e.g. that exceed the force stop waiting time) it may lead to Kodi hanging on shutdown. In case your addon needs long sleep/idle periods use xbmc.Monitor().waitForAbort(secs) instead.

**Comment by im85288** [comment]
So with our 5 seconds we were on the border of it being a long sleep.

**Comment by dagwieers** [comment]
@im85288 I don't think that code block is correct. I would expect only the `xbmc.sleep(5000)` needs to be replaced with `xbmc.Monitor().waitForAbort(5000)`. The while-loop is not needed.

**Comment by dagwieers** [comment]
For the second remark, this is actually broken down into much smaller sleeps, totalling to 10 seconds. So I don't think it is a problem.

**Comment by im85288** [comment]
@dagwieers does it not need the `abortRequested` to allow it to break out? The two have to be used together I thought...

**Comment by im85288** [comment]
@dagwieers actually scrap that your correct, it's not needed here

**Comment by dagwieers** [comment]
Probably best to untag, and retag v1.1.1. This has always been an issue: you mark a new release, and then it requires changes by Kodi devs. That workflow is not perfect.

**Comment by im85288** [comment]
Ok committed that, so just the script.py to be resolved. 

After we do that do you know how to force push to the appropriate repos (Leia/Matrix)?

**Comment by im85288** [comment]
Ahh you just answered my query!

**Comment by dagwieers** [comment]
I would close both PRs, and untag/retag.

**Comment by im85288** [comment]
Ok, but what about script.py do you want to wait for feedback or change to waitForAbort?

**Comment by dagwieers** [comment]
That is a good question, in this case let us test ourselves. Our unit-tests don't cover this bit yet.

**Comment by im85288** [comment]
This would do it?

```
 while popup and step < timeout and not xbmc.Monitor().abortRequested():
        if popup.pause:
            continue
        xbmc.Monitor().waitForAbort(wait)
        popup.update_progress_control(timeout, wait)
        step += wait
```

**Comment by im85288** [comment]
Hmm I broke the build:
```

resources/lib/player.py:34:8: E0602: Undefined variable 'xbmc' (undefined-variable)
10
resources/lib/player.py:5:0: W0611: Unused sleep imported from xbmc (unused-import)
```

**Comment by dagwieers** [comment]
Hmm, the abortRequested is probably useful, but we sleep for 100ms.
On the other hand, the biggest issue is probably the instantiating of Monitor.
So probably better to instantiate it first and then reuse it.

**Comment by dagwieers** [comment]
Yes, if we are no longer using `xbmc.sleep` we don't need to import it.

**Comment by dagwieers** [comment]
So I would only go for doing `abortRequested()` on an instantiated `Monitor()` and leave the sleep in place. I think the overhead of doing a `waitForAbort()` for 100ms is probably not worth it.

**Comment by im85288** [comment]
@dagwieers Ok cool go for it...it's basically down to the Kodi devs though if they accept it.

**Comment by im85288** [comment]
Fixed the failing test :)

**Comment by im85288** [comment]
@dagwieers so we can go for:

```
monitor = Monitor()
    while popup and step < timeout and not monitor.abortRequested():
        if popup.pause:
            continue
        monitor.waitForAbort(wait)
        popup.update_progress_control(timeout, wait)
        step += wait
```

or 

```
monitor = Monitor()
    while popup and step < timeout and not monitor.abortRequested():
        if popup.pause:
            continue
        sleep.(wait)
        popup.update_progress_control(timeout, wait)
        step += wait
```

**Comment by im85288** [comment]
As it's only used for testing and they picked up on it let's just go for the waitForAbort...easy life :)

**Comment by anxdpanic** [comment]
You can use `waitForAbort(time)` as condition as well.
```python
monitor = Monitor()
while popup and step < timeout and not monitor.abortRequested():
	if popup.pause:
		continue
	if monitor.waitForAbort(wait):
		break
	popup.update_progress_control(timeout, wait)
	step += wait
```

**Comment by Razzeee** [comment]
Any plan on pushing this to the official repo?
Seems like users already started using it and I'm not sure if I should even look at issues with unreleased changed https://github.com/trakt/script.trakt/issues/519

**Comment by im85288** [comment]
Not sure what the status is here, reading the comments it seemed like the change was only used in our test class but I'm sure @dagwieers knows more.

**Comment by dagwieers** [comment]
I have no clue what this is about. Both the original issue was fixed (v1.1.1) as well as the above change (which was not an actual problem, only a preference of the reviewers) was released in v1.1.2 by @im85288 in https://github.com/im85288/service.upnext/commit/82c6b725a9737e25112e2d3ebecc5e76bf251ac2.

**Comment by Razzeee** [comment]
As far as I remember this issue the aim was to have a version that is available via the repo. I'm not seeing it being available on my main setup running Kodi Matrix, do you?

I think I could have made that more clear in the issue body.

**Comment by dagwieers** [comment]
I think it is available. It is being downloaded. http://mirrors.kodi.tv/stats?downloadstats&filter=service.upnext

**Comment by Razzeee** [comment]
You're right, I missed it when looking at http://mirrors.kodi.tv/addons/matrix/ 
Sorry!

**Comment by dagwieers** [comment]
No worries. We might as well had an issue we did not know about. Thanks for caring!
