### ISSUE TITLE
Continue Watching Not Working Correctly

### ISSUE THREAD

**Issue by tmortonorr** [im85288/service.upnext#19]
If you let the continue watching popup to timeout and auto play the next episode, instead of playing the next episode it seems to start playing the first episode from that session. If you press the continue watching button it works correctly.

**Comment by angelblue05** [comment]
Do you still have this issue? I can't seem to replicate this. What is the add-on that fills the info for up next?

**Comment by angelblue05** [comment]
This issue can be closed, it should be resolved with 1.0.1
