### ISSUE TITLE
Use with "Play next video automatically"

### ISSUE THREAD

**Issue by ltGuillaume** [im85288/service.upnext#203]
I am using Kodi via LibreELEC on a Raspberry Pi 2, without the use of the library. I'm trying to get Up Next to work when I start playing a single file on an SMB share with several files in the same path.

In the Kodi settings under Player > Videos, there's the option "Play next video automatically", which automatically adds other files in a folder to Kodi's playlist (queue).

I assumed that this is the playlist (queue) that Up Next refers to in its settings ("Enable on playlists"), but am I wrong? Does Up Next only work for saved playlists?

If so, can Up Next also be made to work for Kodi's ad-hoc playlist/the queue?

__Edit__: I may have searched the issues with the wrong keywords, may be duplicate of #199. But trying the latest master (with #198 merged) did not change anything.

**Comment by dagwieers** [comment]
I would expect this to work already. There should not be a difference in how this works for local or SMB/NFS content. (I am using NFS myself).

In all three cases, we rely on Kodi's media library to know what the next episode is based on the existing episode and the information stored in Kodi. We do not need the "Play next video automatically" to be enabled. There is no advantage to have this, if you have Up Next installed.

Please share your Kodi debug log (preferably, restart and perform a minimum set of action to reproduce this) so we can see what Up Next is doing.

**Comment by ltGuillaume** [comment]
Aha, but there is! I do not use the Kodi library in any way: none of the local and SMB locations I have set up are included in the Kodi database. 

As such, Up Next won't be able to find the next episode in the database, but it _would_ be able to honor the next playlist item.

I thought this would be where the setting "Enable on playlists" would come in. I'd say it's rather confusing that it doesn't.

I went through the debug log, but there is no mention at all of Up Next trying to find a file to play next, but that makes sense if it only considers entries from the database.

**Comment by dagwieers** [comment]
So the main question remains why Kodi is not playing the next file. What type of files did you select in the settings? I assume Kodi does not know what is a series or a movie if it did not index the files...

But I think we can close the ticket.

**Comment by ltGuillaume** [comment]
Kodi does add the files to the playlist and it will play the next file when it's at the end of a file. I just thought that "Enable on playlist" would trigger the Up Next popup 30 seconds (or custom time) before the end, because there's a next item in Kodi's playlist. Apparently it doesn't.

**Comment by ltGuillaume** [comment]
> I just thought that "Enable on playlists" would trigger the Up Next popup (...) Apparently it doesn't.

Should it (for Kodi's own queue/playlist)? Or is it by design that it doesn't, and did I misunderstand the option?

**Comment by dagwieers** [comment]
@ltGuillaume I don't know what this option does, honestly. It was removed in v1.0.2
> - Remove enablePlaylist setting (@angelblue05) https://github.com/im85288/service.upnext/commit/91d41bad41d0eb139a752d766b1511b70adb3f73

And then re-added in v1.1.1
> - Restore "Ignore Playlist" option (@BrutuZ) https://github.com/im85288/service.upnext/commit/078763eb53ebcc5c48d7e15988448c3ac4952b06

**Comment by ltGuillaume** [comment]
Thanks. That "re-adding" also confused me, as the description "Ignore playlist" is opposite to what the current settings (in the current master) said: "Enable on playlists". It made me think the setting might be reversed to what the UI suggests.

**Comment by dagwieers** [comment]
Well, an option to enable something, is also an option to disable something. So I would not read too much into it.

**Comment by BrutuZ** [comment]
As mentioned above, UpNext uses information from the Kodi DB to know whether or not to show the pop-up and to which episode. If you're not using the DB at all, the plugin have no information to show the pop-up.

I inverted the setting's label when re-adding it after the project refactor and renaming (NextUp > UpNext) just for consistency of options enabling certain functionality \ behavior. Having a active toggle to disable something felt counter-intuitive.

The only effect of "Enable on Playlists" is whether or not UpNext is allowed to break the current queue if one of its episodes has a sequel.
Use-case examples:
- **Toggled On:** Smart playlist of weekly episodes sorted by airing date, you're watching different shows until that one episode that ends in a cliffhanger and you want to skip to its next episode instead of another show.
- **Toggled Off:** You queue up an entire season to binge watch and don't need \ want the pop-ups in the middle of your sessions. Especially since UpNext doesn't remove queue items, it will continue playing regardless of your choice to not play the next episode.

**Comment by ltGuillaume** [comment]
> As mentioned above, UpNext uses information from the Kodi DB to know whether or not to show the pop-up and to which episode. If you're not using the DB at all, the plugin have no information to show the pop-up.

You're absolutely right, I somehow completely overlooked the fact that in this case, the only info would be the filenames.

> Having a active toggle to disable something felt counter-intuitive.
Yes, that makes sense. When I saw the changelog and since I thought using the user playlist without Kodi DB should also work, I was unsure if the option was properly "inverted".

Thanks for explaining the feature. It's much clearer now what I can Up Next for. Much obliged.
