### ISSUE TITLE
LOGSEVERE and LOGNOTICE will deprecated in kodi/python addons

### ISSUE THREAD

**Issue by phunkyfish** [im85288/service.upnext#205]
Please replace with LOGFATAL and LOGINFO. They will be removed in a couple of weeks.

PR: https://github.com/xbmc/xbmc/pull/18346
Forum Post: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by im85288** [comment]
@MoojMidge  @dagwieers  Where are we with this one? It's starting to fail on Nightlies so want to either merge in or update

**Comment by MoojMidge** [comment]
Just created a PR to address this specific issue (#213).

I was looking for a bit of guidance about the larger changes in case it was needed to reformat/restructure things, as I had previously already gone ahead and made a number of changes that impact on the module structure and formatting (https://github.com/im85288/service.upnext/pull/206#issuecomment-686188449)

**Comment by im85288** [comment]
Thanks that's merged now. Let's give @dagwieers some time to come back with feedback on your other PR's as he is more up to date with the latest code base than I am. If we haven't heard back in say a week I'll step in. Your changes look cool so we will get them in some how, cheers

**Comment by rikardfries** [comment]
I may be to fast here with my comment, but I do not see the update in Kodi yet..

**Comment by phunkyfish** [comment]
It’s merged, here: https://github.com/xbmc/xbmc/pull/18346

**Comment by rikardfries** [comment]
Sorry for the confusion, my apoligies, I meant the service.upnext update.

> It’s merged, here: [xbmc/xbmc#18346](https://github.com/xbmc/xbmc/pull/18346)

**Comment by im85288** [comment]
It’s currently only merged with the latest and greatest, so if using a nightlie version of Kodi you would need to get the code directly. A release will come at some stage but not quite yet.

**Comment by rikardfries** [comment]
> It’s currently only merged with the latest and greatest, so if using a nightlie version of Kodi you would need to get the code directly. A release will come at some stage but not quite yet.

Ah, perfect then I understand. Thank you.

**Comment by dagwieers** [comment]
We are preparing the release of v1.1.3, please help in testing this as wide as possible.
