### ISSUE TITLE
Extend the time before the notification

### ISSUE THREAD

**Issue by simonbcn** [im85288/service.upnext#21]
There are TV shows whose credit titles last longer than 1 minute.

**Comment by notoco** [comment]
https://github.com/im85288/service.upnext/issues/11#issuecomment-462773005

**Comment by simonbcn** [comment]
Yes, I've tried it and it works but the notification still shows only 60 seconds. Where can I change this behavior?

**Comment by angelblue05** [comment]
This has been added with the latest release. @im85288 please close this.

**Comment by im85288** [comment]
Closed thanks
