### ISSUE TITLE
Compatibility with PKC and Kodi DSPlayer (v17)

### ISSUE THREAD

**Issue by camjac251** [im85288/service.upnext#214]
I am having difficulty getting this to work with PlexKodiConnect and Kodi DSplayer. I am getting this error when I try starting up an item. Maybe with the way PlexKodiConnect and Plex operates, is this plugins not compatible?

This is what the error log shows. I've redacted it a bit though.
```
12:22:55.467 T:20360  NOTICE: PLEX.TVSHOWS: PKC add-on for tv shows started
12:22:55.718 T:16728  NOTICE: PLEX.playback_decision: User chose playback method DirectPath in PKC settings
12:22:55.722 T:16728  NOTICE: PLEX.playback_decision: PKC decided on playback method DirectPlay
12:22:55.765 T:16728  NOTICE: PLEX.playback_decision: Lets ask the PMS next
12:22:55.765 T:16728  NOTICE: PLEX.playback_decision: Asking PMS with maximal quality settings
12:22:55.814 T:16728  NOTICE: PLEX.playback_decision: PMS general decision None: None
12:22:55.814 T:16728  NOTICE: PLEX.playback_decision: PMS Direct Play decision None: None
12:22:55.814 T:16728  NOTICE: PLEX.playback_decision: PMS MDE decision 1000: Direct play OK.
12:22:55.814 T:16728  NOTICE: PLEX.playback_decision: PMS transcoding decision None: None
12:22:55.814 T:16728  NOTICE: PLEX.playback_decision: The playurl for DirectPlay is: https://ID.plex.direct:port/library/parts/number/number2/file.mkv?Accept-Language=en&X-Plex-Platform=Generic&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=Token&X-Plex-Model=10&X-Plex-Platform-Version=1.0.0&X-Plex-Client-Identifier=identifier&Accept=%2A%2F%2A&X-Plex-Device=Windows&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.12.3
12:22:55.821 T:16728  NOTICE: PLEX.api: Found external subs: []
12:22:55.826 T:20360  NOTICE: PLEX.TVSHOWS: PKC add-on for tv shows stopped
12:22:56.067 T:280  NOTICE: CDSPlayer::OpenFile - DSPlayer: Opening: https://ID.plex.direct:port/library/parts/number/number2/file.mkv?Accept-Language=en&X-Plex-Platform=Generic&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=Token&X-Plex-Model=10&X-Plex-Platform-Version=1.0.0&X-Plex-Client-Identifier=identifier&Accept=%2A%2F%2A&X-Plex-Device=Windows&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.12.3
12:22:56.067 T:280  NOTICE: CDSPlayer::OpenFileInternal - DSPlayer: Opening: https://ID.plex.direct:port/library/parts/number/number2/file.mkv?Accept-Language=en&X-Plex-Platform=Generic&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=Token&X-Plex-Model=10&X-Plex-Platform-Version=1.0.0&X-Plex-Client-Identifier=identifier&Accept=%2A%2F%2A&X-Plex-Device=Windows&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.12.3
12:22:56.067 T:6748  NOTICE: CDSPlayer::Process - Creating DS Graph
12:22:56.074 T:6748  NOTICE: Loading filter core factory settings from special://xbmc/system/players/dsplayer/filtersconfig_internal.xml (filters configuration).
12:22:56.077 T:6748  NOTICE: Loading filter core factory settings from special://profile/dsplayer/filtersconfig.xml (filters configuration).
12:22:56.077 T:6748  NOTICE: Loading filter core factory settings from special://xbmc/system/players/dsplayer/filtersconfig.xml (filters configuration).
12:22:56.083 T:6748  NOTICE: Loading filter core factory settings from special://xbmc/system/players/dsplayer/mediasconfig_internal.xml (medias configuration).
12:22:56.083 T:6748  NOTICE: Successfully loaded rules
12:22:56.103 T:6748  NOTICE: CFGLoader::InsertAudioRenderer Successfully added internal sanear audio renderer to the graph
12:22:56.351 T:6748  NOTICE: CFGLoader::InsertFilter Successfully added "(i) LAV Splitter Source" to the graph
12:23:00.213 T:6748  NOTICE: CFGLoader::InsertSourceFilter Successfully loaded file in the splitter/source
12:23:00.220 T:6748  NOTICE: CFGLoader::InsertFilter Successfully added "(i) XySubFilter" to the graph
12:23:00.221 T:6748  NOTICE: CStreamsManager::LoadIAMStreamSelectStreamsInternal Audio stream found : Surround 5.1 [eng] (dts-hd ma, 48000 Hz, 5.1, s16) - index: 1
12:23:00.221 T:6748  NOTICE: CStreamsManager::LoadIAMStreamSelectStreamsInternal Subtitle stream found : English [eng] (pgs) - index: 2
12:23:00.221 T:6748  NOTICE: CStreamsManager::LoadIAMStreamSelectStreamsInternal Subtitle stream found : Forced Subtitles (auto) - index: 3
12:23:00.221 T:6748  NOTICE: CStreamsManager::LoadIAMStreamSelectStreamsInternal Subtitle stream found : No subtitles - index: 4
12:23:00.221 T:6748  NOTICE: CSubtitleManager::Initialize disabled libsubs.dll
12:23:00.433 T:6748  NOTICE: CFGLoader::InsertFilter Successfully added "(i) LAV Video" to the graph
12:23:00.435 T:6748  NOTICE: CFGLoader::InsertFilter Successfully added "(i) LAV Audio" to the graph
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 01" found. Start time: 0
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 02" found. Start time: 260593
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 03" found. Start time: 963212
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 04" found. Start time: 1668541
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 05" found. Start time: 2101015
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 06" found. Start time: 2869783
12:23:00.509 T:21096  NOTICE: CChaptersManager::LoadChapters Chapter "Chapter 07" found. Start time: 3406569
12:23:05.651 T:8704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'UpNextPlayer' object has no attribute 'isExternalPlayer'
                                            Traceback (most recent call last):
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\service_entry.py", line 8, in <module>
                                                UpNextMonitor().run()
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\monitor.py", line 49, in run
                                                if self.player.isExternalPlayer():
                                            AttributeError: 'UpNextPlayer' object has no attribute 'isExternalPlayer'
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
I don't see why it wouldn't work, however you have to ensure that playback has started before signaling Up Next. I think that may have happened here. Do you have a link to your integration?

**Comment by camjac251** [comment]
Sure. I'm using https://github.com/croneter/PlexKodiConnect and https://forum.kodi.tv/showthread.php?tid=223175 (64-bit version). Not sure if the Kodi skin is also the cause but I'm using Aura.

**Comment by dagwieers** [comment]
@camjac251 I am confused, you did not integrate Up Next into an existing add-on? But it crashes when using PKC and having Up Next installed?

**Comment by camjac251** [comment]
That is my fault for not reading the readme close enough. I wasn't aware that this isn't a standalone addon if I understand you correctly. I was thinking it'd be as simple as installing the latest release https://github.com/im85288/service.upnext/releases/tag/v1.1.2 and it would start working

**Comment by im85288** [comment]
I used to do a bit of dev on PKC, I’m a nutshell it writes things to Kodi’s database so media is played back as being native to Kodi.

So in other words it should and always has worked well with this addon.

It looks like the issue here is using an external player (DSPlayer), I have never tried that combination. Perhaps try without DSPlayer in the mix to confirm it’s the external player it is having issues with.

**Comment by dagwieers** [comment]
Up Next is a standalone add-on for locally hosted media. It uses the library for any metadata (and to find the next episode to play).
Any other add-on needs to feed Up Next with the metadata (and a means of playing the next episode) after starting playback.

**Comment by dagwieers** [comment]
@im85288 I am surprised in this case that `isExternalPlayer()` is missing from the Player object. According to the documentation, this is Kodi v18 functionality.

**Comment by im85288** [comment]
> Up Next is a standalone add-on for locally hosted media. It uses the library for any metadata (and to find the next episode to play).
> Any other add-on needs to feed Up Next with the metadata (and a means of playing the next episode) after starting playback.

PKC does that under the hood (same as Emby for Kodi which it was copied from), writes the movies and tvshows from Plex into kodi’s library to allow max compatibility with other addons (like this one).

**Comment by im85288** [comment]
> @im85288 I am surprised in this case that `isExternalPlayer()` is missing from the Player object. According to the documentation, this is Kodi v18 functionality.
> https://codedocs.xyz/AlwinEsch/kodi/group__python___player.html#ga802ed7f337e16e957ec31555a95814b0

Yeah looks like he is running this on Kodi v17 where that functionality was not present. I think we can close this one once he confirms.

**Comment by im85288** [comment]
The older next up addon is for Kodi 17 and before, this up next one supports Kodi 18 onwards.

**Comment by camjac251** [comment]
Oh I see. I think I tried the "Service - Next Up" in the Repository but during the last 30 seconds, nothing had appeared. Kodi DSPlayer is based on v17.6. I use DSplayer because it allows external renderers like madVR (nicer tonemapping from HDR to SDR).

**Comment by dagwieers** [comment]
@im85288 I have a fix for Kodi v17 ready to avoid this specific case. We can test it if @camjac251 likes to.

**Comment by camjac251** [comment]
This addon is able to work or do you mean the older Next Up one. I am happy to test anything for v17.

**Comment by im85288** [comment]
@dagwieers that’s cool, officially no Kodi 17 support but I’m sure he will be happy to try it.

**Comment by dagwieers** [comment]
@im85288 We can try, maybe it is easy to do, maybe it is impossible.

**Comment by dagwieers** [comment]
@camjac251 Can you try PR #215 ?

**Comment by camjac251** [comment]
Before this patch, I'd see an error at the top right saying that UpNext outputted something to log. That doesn't show up anymore. Although I tried to test two files and at the 1 minute left mark and after, nothing had shown up on screen. I'm guessing since it is an external player (madvr in this case but using dsplayer), it is not able to output over it. However, running the tests in the settings menu did work when I tried.

I do have this issue though with the logging. I changed `LOGINFO` to `LOGNOTICE` in the utils.py to fix it though. The error was with the exact code in the PR.
```
14:38:49.377 T:9376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'LOGNOTICE' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\service_entry.py", line 8, in <module>
                                                UpNextMonitor().run()
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\monitor.py", line 29, in run
                                                self.log('Service started', 0)
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\monitor.py", line 25, in log
                                                ulog(msg, name=self.__class__.__name__, level=level)
                                              File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\utils.py", line 146, in log
                                                level = LOGDEBUG if debug_logging else LOGNOTICE
                                            NameError: global name 'LOGNOTICE' is not defined
                                            -->End of Python script error report<--
```

**Comment by camjac251** [comment]
Here's the source code for Kodi DSPlayer. I've always hoped someone could make a newer release but aracnoz seemed to be the only one who did

https://github.com/aracnoz/xbmc

**Comment by dagwieers** [comment]
> Thank you for the fast patch, @dagwieers. Before this patch, I'd see an error at the top right saying that UpNext outputted something to log. That doesn't show up anymore. Although I tried to test two files and at the 1 minute left mark and after, nothing had shown up on screen. I'm guessing since it is an external player (madvr in this case but using dsplayer), it is not able to output over it. However, running the tests in the settings menu did work when I tried.
> 
> I do have this issue though with the logging. I changed `LOGINFO` to `LOGNOTICE` in the utils.py to fix it though. The error was with the exact code in the PR.
> 
> ```
> 14:38:49.377 T:9376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.NameError'>
>                                             Error Contents: global name 'LOGNOTICE' is not defined
>                                             Traceback (most recent call last):
>                                               File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\service_entry.py", line 8, in <module>
>                                                 UpNextMonitor().run()
>                                               File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\monitor.py", line 29, in run
>                                                 self.log('Service started', 0)
>                                               File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\monitor.py", line 25, in log
>                                                 ulog(msg, name=self.__class__.__name__, level=level)
>                                               File "C:\Users\User\Documents\kodidsp\portable_data\addons\service.upnext\resources\lib\utils.py", line 146, in log
>                                                 level = LOGDEBUG if debug_logging else LOGNOTICE
>                                             NameError: global name 'LOGNOTICE' is not defined
>                                             -->End of Python script error report<--
> ```

Yup, someone added support for the latest Kodi development tree, and broke support for the stable tree.
https://github.com/im85288/service.upnext/pull/213/files

Personally I am fed up with Kodi breaking stuff at the end of a release cycle, rather than doing this at the beginning of a release cycle so add-ons are not forced to catch up with whatever backward compatibility breakage they are introducing during beta/release candidates. They are forcing pain on their most important stakeholders. Bad management.

**Comment by camjac251** [comment]
I tested it again this morning and it works beautifully. Thank you again @dagwieers it is working quite nicely with PKC and Kodi DSplayer (on Aura skin). I also like that it doesn't start the next file until the first one finishes entirely.

**Comment by im85288** [comment]
@dagwieers Nice work

**Comment by dagwieers** [comment]
@im85288 This is mostly your work, I am just meddling in the margin ;-)
