### ISSUE TITLE
Feature Request: reset 'still watching' state

### ISSUE THREAD

**Issue by jonesthefox** [im85288/service.upnext#22]
Hey there, thanks for your good work, it's a really useful addon. 

Is it possible to reset the 'still watching' state after stopping the video when the 'still watching' button is not pressed?

Let's say, i watch i.e. 5 episodes and i was too lame to press that button, i then select the next episode and have to press the 'still watching' button when the episode ends, that i can watch the next 5 episodes without touching my remote. 
The behauvior should be, that it plays my 5 episodes and ask me then 'are you still there?'..

**Comment by im85288** [comment]
Should be resolved with the above PR
