### ISSUE TITLE
(Question)

### ISSUE THREAD

**Issue by mathu204** [im85288/service.upnext#235]
Hi im playing around with the .xml, and ive managed to change the blue backgrounds of the buttons to Red, but I cant seem to figure out how to change the pink countdown text would u mind pointing me to where that is? in Upnext-upnext, (Fancy).

**Comment by dagwieers** [comment]
The easiest way to find this is by checking the string-id of the message you are seeing from the translations.

https://github.com/im85288/service.upnext/blob/1e5a8813cd33a7d46af5f2f838fb572358faf303/resources/language/resource.language.en_gb/strings.po#L57-L59

Then find that ID inside of the skin.
https://github.com/im85288/service.upnext/blob/1e5a8813cd33a7d46af5f2f838fb572358faf303/resources/skins/default/1080i/script-upnext-upnext.xml#L93-L102

**Comment by dagwieers** [comment]
I assume this answers your question, if not, let me know.

**Comment by mathu204** [comment]
> I assume this answers your question, if not, let me know.

THanks it did
