### ISSUE TITLE
Feature Request for the next episode playing at the same tempo as the current

### ISSUE THREAD

**Issue by Dnkhatri** [im85288/service.upnext#24]
Sometimes I watch stuff at a faster tempo but currently have to manually change the tempo after each episode so the usefulness of the plugin decreases for me I want the upnext plugin to check the playback tempo and keep it for the next episode

**Comment by angelblue05** [comment]
I honestly have no idea what you are referring to? Why should up next be in charge of this behavior? And how do I setup something like that?

**Comment by Dnkhatri** [comment]
> I honestly have no idea what you are referring to? Why should up next be in charge of this behavior? And how do I setup something like that?

You have to enable sync playback to display once you do that you do that you can change the tempo the video is played at in kodi by pressing alt+right or left arrow. If I am playing an episode at 1.5x speed once the episode finishes and upnext starts the new episode the new episode starts at normal playback speed where as I would like it to keep playing at the same speed as the previous episode.

**Comment by angelblue05** [comment]
I believe this should be a FR for Kodi itself. Unless you tell me that without using up next, but using the regular kodi play next automatically, Kodi keeps the speed from the first video?

@im85288 your opinion on this is needed. It is your project.

**Comment by im85288** [comment]
Yes agreed, not something this addon will handle

**Comment by Dnkhatri** [comment]
Okay I checked when I don't press the play next button the tempo for the next episode stays at @1.5 . But if play next it doesn't. So kodi does play next doesn't. @angelblue05 @im85288  

> I believe this should be a FR for Kodi itself. Unless you tell me that without using up next, but using the regular kodi play next automatically, Kodi keeps the speed from the first episode?
> 
> @im85288 your opinion on this is needed. It is your project.

**Comment by angelblue05** [comment]
@Dnkhatri did you get a chance to try the PR to confirm this is indeed resolved now?

**Comment by Dnkhatri** [comment]
Ah sorry pressed close issue  wrongly as far as I can tell  no difference if I don't press the play next button the tempo is maintained if do the new episodes starts a 1 tempo

**Comment by angelblue05** [comment]
Where does the content come from? Is it from Kodi or some addon? Does it make a difference if you also enable play next automatically in the Kodi settings?

**Comment by Dnkhatri** [comment]
> Where does the content come from? Is it from Kodi or some addon? Does it make a difference if you also enable play next automatically in the Kodi settings?

The content is from kodi my kodi play next was off so I tried with it on made no difference.

**Comment by angelblue05** [comment]
@Dnkhatri 
So I was curious and set up tempo on my side. Even without up next, only using Kodi auto play next, the tempo is not maintained moving to the next playlist item, therefore, it is not fixable and you should make the FR on the Kodi forums instead. 

As I said above, up next now gives priority to the existing playlist. When you select watch now, it simply seeks to the end of the video and kodi kicks in as normal

**Comment by Dnkhatri** [comment]
> @Dnkhatri
> So I was curious and set up tempo on my side. Even without up next, only using Kodi auto play next, the tempo is not maintained moving to the next playlist item, therefore, it is not fixable and you should make the FR on the Kodi forums instead.
> 
> As I said above, up next now gives priority to the existing playlist. When you select watch now, it simply seeks to the end of the video and kodi kicks in as normal If that doesn't work, it's simply because Kodi does not maintain the tempo when moving to the item, as I asked you previously. You stated otherwise, was it a fluke?

Increase tempo but don't press play next button when it shows up let it start on its own. When the next episode starts it will start at the higher tempo this works for me I have tried it with multiple shows and it works.

**Comment by angelblue05** [comment]
That’s what I did, I enable sync playback to display. I increase the tempo for the episode. Let it play until the end, then the next episode is regular speed again...

You even said, play next + watch now in up next just seeks to the end of the episode. If you seek to the end, and then it moves on to the next episode, is the tempo maintained?

**Comment by Dnkhatri** [comment]
> That’s what I did, I enable sync playback to display. I increase the tempo for the episode. Let it play until the end, then the next episode is regular speed again...
> 
> play next + watch now in up next just seeks to the end of the episode. If you seek to the end, and then it moves on to the next episode, is the tempo maintained?

I have set upnext at 1 min. Then I skip the episode till before the upnext button shows up then let it play out 1 min+ to the end. The next episode starts at the higher tempo. The built in kodi playnext I have disabled for everything tvshow or episodes.

**Comment by angelblue05** [comment]
That is not exactly what I asked. What happens if you seek to the end of the file, so that it plays the next video, does it keep the play speed?

Also, is this with my latest changes you are testing with? Thanks.

**Comment by Dnkhatri** [comment]
> That is not quite what I asked. What happens if you seek to the end of the file (not one minute before), so that it plays the next video, does it keep the play speed? (It doesn't help that I can't maintain the play speed between playlist items... Then I can't see for myself.
> 
> Also, is this with my latest changes you are testing with? Thanks.

I downloaded the plugin from your github so should have your latest changes. The tempo does not stay high if I seek to the end

**Comment by im85288** [comment]
Closing this issue as it will not be handled in the addon
