### ISSUE TITLE
[Netflix][UpNext][Library] - neverending errors

### ISSUE THREAD

**Issue by notoco** [im85288/service.upnext#240]
Honestly, I'm starting to give up. I described the problem [here](https://github.com/CastagnaIT/plugin.video.netflix/issues/991), but there were other errors ...
http://ix.io/2J9Y

Before there was a Netflix bug, now there is an Upnext bug. From several versions of these two plugins, they refuse to cooperate when using the kodi library

**Comment by MoojMidge** [comment]
There is a bug in UpNext here but that is not what is causing the problem.

UpNext checks if addon data is being provided and then checks if play_url is being sent as part of the addon data. If play_url is not being sent, then UpNext assumes that play_info is being sent instead and tries to use that, without checking if play_info actually exists.

This can be easily fixed, but the actual problem is that the play_url data being sent from the Netflix addon is just an empty string, and so UpNext can't really do anything with the addon data.

The log file and the code used to generate play_url for strm files looks OK (from a cursory look, given that I'm not too familiar with the Netflix addon), but for whatever reason the location of the next strm file is not being found correctly. Perhaps the actual database query is not working because the strm files have been relocated? @CastagnaIT would be the best person to advise further.

**Comment by CastagnaIT** [comment]
The played video is a STRM there is no doubt here:
`2020-12-22 18:23:26.720 T:140445137061440    INFO: [plugin.video.netflix (2)] Playing episode_80104023 [STRM file] [external call]`

On the line 1198 there is the upnext data sent:
<pre>
{
    u 'play_url': u '',
    u 'next_episode': {
        u 'rating': 6.7,
        u 'tvshowid': u '80104022',
        u 'art': {
            u 'tvshow.fanart': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRGjbAJH7V1OuVFtXhrRp4D6jbXNqyGjoxT_-_MwYSmH6lU2GaIOEv5_Aj-qKNKG_DPgA7Nab0F-L_F-WRrmh2m7JX_9enq9XcjLQl6MhJboe2XVIw.jpg?r=d77',
            u 'thumb': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRGjbAJH7V1OuVFtXhrRp4D6jbXNqyGjoxT_-_MwYSmH6lU2GaIOEv5_Aj-qKNKG_DPgA7Nab0F-L_F-WRrmh2m7JX_9enq9XcjLQl6MhJboe2XVIw.jpg?r=d77',
            u 'tvshow.clearart': u '',
            u 'tvshow.landscape': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABRGjbAJH7V1OuVFtXhrRp4D6jbXNqyGjoxT_-_MwYSmH6lU2GaIOEv5_Aj-qKNKG_DPgA7Nab0F-L_F-WRrmh2m7JX_9enq9XcjLQl6MhJboe2XVIw.jpg?r=d77',
            u 'tvshow.poster': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRtXAaIlIC3ZsceUyi5Lj08mTnkwCTivpQezYH-Qb94syJfALxV32wVdS7K3irgDB7R4zASYEoe4Ue-k3KtcG1F3I_qC.jpg?r=574',
            u 'tvshow.clearlogo': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABajy0gG624Ty4JOF1y8re5saiFg5qex5N7bh5ELSio7S-NvQKkrBwdry2oQQWmBnPLJb9W0R0Vz-GLyXwfM5tySUzMM0RR4NBQ.png?r=ac6'
        },
        u 'plot': u 'S\u0105 bardzo r\xf3\u017cne, a\xa0jednak uroczy torbacz kuoka i\xa0kangur staj\u0105 przeciwko malutkim s\u0142oniom i\xa0kozom w\xa0konkursie o\xa0tytu\u0142 najs\u0142odszego zwierzaka.',
        u 'season': u '1',
        u 'title': u 'Brykaj\u0105ce stworzenia',
        u 'episodeid': u '80104024',
        u 'firstaired': 2016,
        u 'episode': u '2',
        u 'playcount': 0,
        u 'runtime': 1619,
        u 'showtitle': u '72 Cutest Animals'
    },
    u 'notification_offset': 1587,
    'id': u 'plugin.video.netflix_play_action',
    u 'current_episode': {
        u 'rating': 6.7,
        u 'tvshowid': u '80104022',
        u 'art': {
            u 'tvshow.fanart': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUSqRjGGMUO4ak3dshQ-RKu5HyU1UXJtpRFnK8H2oRGeZdkslYQ7GJe1Rc816Zopv7bJe-TzDXY-Yst1mYNP5zs6sA5-42yuaJeDrZtTPStPCRAiRw.jpg?r=50e',
            u 'thumb': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUSqRjGGMUO4ak3dshQ-RKu5HyU1UXJtpRFnK8H2oRGeZdkslYQ7GJe1Rc816Zopv7bJe-TzDXY-Yst1mYNP5zs6sA5-42yuaJeDrZtTPStPCRAiRw.jpg?r=50e',
            u 'tvshow.clearart': u '',
            u 'tvshow.landscape': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABUSqRjGGMUO4ak3dshQ-RKu5HyU1UXJtpRFnK8H2oRGeZdkslYQ7GJe1Rc816Zopv7bJe-TzDXY-Yst1mYNP5zs6sA5-42yuaJeDrZtTPStPCRAiRw.jpg?r=50e',
            u 'tvshow.poster': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRtXAaIlIC3ZsceUyi5Lj08mTnkwCTivpQezYH-Qb94syJfALxV32wVdS7K3irgDB7R4zASYEoe4Ue-k3KtcG1F3I_qC.jpg?r=574',
            u 'tvshow.clearlogo': u 'https://occ-0-1432-1433.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABajy0gG624Ty4JOF1y8re5saiFg5qex5N7bh5ELSio7S-NvQKkrBwdry2oQQWmBnPLJb9W0R0Vz-GLyXwfM5tySUzMM0RR4NBQ.png?r=ac6'
        },
        u 'plot': u 'R\xf3\u017cne zwierz\u0119ta rywalizuj\u0105 o\xa0tytu\u0142 kr\xf3la wdzi\u0119ku tego odcinka. W\u015br\xf3d nich znalaz\u0142y si\u0119 mi\u0119kki i\xa0sympatyczny koala, goryl i\xa0czarny ko\u0144 po\u015br\xf3d kandydat\xf3w, czyli o\u015bmiornica.',
        u 'season': u '1',
        u 'title': u 'Nie tylko puszysto\u015b\u0107',
        u 'episodeid': u '80104023',
        u 'firstaired': 2016,
        u 'episode': u '1',
        u 'playcount': 0,
        u 'runtime': 1622,
        u 'showtitle': u '72 Cutest Animals'
    }
}
</pre>

actually play_url for some reason is empty
i need more info to understand something please @notoco reproduce the error with this:
[plugin.video.netflix_1.12.0_20201228_1.zip](https://github.com/im85288/service.upnext/files/5746497/plugin.video.netflix_1.12.0_20201228_1.zip)
and put a new log

**Comment by notoco** [comment]
As you wish, master
http://ix.io/2K5v

**Comment by CastagnaIT** [comment]
Thanks @notoco we continue in to https://github.com/CastagnaIT/plugin.video.netflix/issues/991 to not spam this Issue
