### ISSUE TITLE
Still watching never stops playback - "played in a row" is always 1

### ISSUE THREAD

**Issue by oracleguy** [im85288/service.upnext#243]
This might be related to issue #135 on Kodi 18.6 on the Ubuntu 20.04 LTS with version 1.1.4 of the addon.

If you look at timestamps 5:16:02, 5:37:10, and 5:59:02, the addon kicks in but always thinks only one episode has been played. So the still watching feature doesn't kick in. I have tried rebooting and the problem persists. Is there any additional data I can collect to help track this down? I have the plugin logging set to debug.

Here are the logs: https://paste.kodi.tv/akuyiqagub.kodi

**Comment by MoojMidge** [comment]
This should be fixed in the current master branch.

You can test it by manually installing the zip file from Github: 
![image](https://user-images.githubusercontent.com/56883549/107444561-e6677500-6b8e-11eb-9acf-a28e27812c0c.png)

**Comment by oracleguy** [comment]
Hi,

I can confirm that the latest master fixed it for me. :) Thank you!
