### ISSUE TITLE
Up next disturbing play random

### ISSUE THREAD

**Issue by nilleiz** [im85288/service.upnext#26]
Hello,

I use the script add-on play random video regularly.
This script is creating a temporary playlist of a season or show I want to to watch with episodes in random order.
Unfortunately even with "activate playlist" disabled the next up pop up comes at the end of every episode and would play the next episode in order. I would expect the pop up to announce the next random episode of the playlist instead of the actual next episode or just don't appear at all when watching a playlist.
I use Kodi 18.2.
Tell me what logs I need to provide if needed.
Kind regards!

**Comment by im85288** [comment]
Hello, the up next addon will always look for the next logical episode to play and not respect the order given by a playlist.

I suggest maybe to disable up.next when using the script your using
