### ISSUE TITLE
UpNext not show popup on CoreElec/LibreElec

### ISSUE THREAD

**Issue by CastagnaIT** [im85288/service.upnext#270]
An user @ValentijnDemeyer report to me a problem with UpNext https://github.com/CastagnaIT/plugin.video.netflix/issues/1292 that not works on LibreElec

Then i have done two tests on two platforms,
the test on Windows (Kodi19/20) the UpNext popup is shown with success before the end of playback
the test on CoreElec the UpNext not works

CoreElec log: [kodi.log.txt](https://github.com/im85288/service.upnext/files/8060013/kodi.log.txt)

the same data is sent to UpNext on both cases

**Comment by MoojMidge** [comment]
I think this is already fixed in master (with #259) just needs a new release

Hopefully @im85288 or @dagwieers can help out

**Comment by im85288** [comment]
Sure will look to get a release out this weekend.

**Comment by CastagnaIT** [comment]
thanks

**Comment by theoden11** [comment]
Hello. I'm wondering why upnext is not showing with Netflix or Disney, since Kodi Matrix (not an update but a full install from scratch). I'm on a Vero 4k with latest OSMC, and everything works fine, except that plugin. However, with TV Shows files on the network or hard drive, no problem, UpNext is showing ! Strange in fact.

**Comment by CastagnaIT** [comment]
has been released or this addon is dead?
just to know if i have to plan the removal since this is broken for the most used Kodi OS's

**Comment by im85288** [comment]
Not as of yet, been offline for a while but will release soon.

**Comment by piejanssens** [comment]
> Not as of yet, been offline for a while but will release soon.
> 

Please 🙏

**Comment by CastagnaIT** [comment]
@im85288 if you have no time to keep alive this project
i can suggest you to give gihub permission someonelse to keep it updated and make new releases
maybe @MoojMidge if interested?

**Comment by im85288** [comment]
@CastagnaIT always happy to have contributors. @MoojMidge happy to add as contributor if your interested.

**Comment by MoojMidge** [comment]
For some reason the release workflow failed previously which is why the Kodi addon submitter never submitted a PR to repo-scripts.

The other thing I should probably note is that the recent fixes are mostly pulled from changes I have made to my own fork which has changed significantly from current master.

If more development is not really planned here, it would be easier for me to maintain my own fork than try to cherry pick and bring across small changes to this repository. 

Either way, happy to help.

**Comment by CastagnaIT** [comment]
these are my thoughts, so not impositions, then do as you prefer:

yes your fork has a lot of changes ~1000 commits
https://github.com/im85288/service.upnext/compare/master...MoojMidge:master

but i can also say that your fork start diverge from one of last commits of current repo:
https://github.com/im85288/service.upnext/commits/d5c46a2b9ae2b98898e12d3fa1483915445c49e5
so merging should not difficult step,
just revert the last few commits of current repo, in order to do a big merge of your branch.

since many users have this repo as reference i could suggest two ways:
- Use Github Transfer feature on this repo to an organization
If a radical change need to be made, could be better consider moving the project in to example https://github.com/add-ons
so that future maintainers will not have to use personal github accounts, and will be able to join directly on the organisation team or place contributors PRs to keep the project updated.
The github feature "transfer repository", allow to transfer all branches/Issues/PR to a new account or organiziation account, more important this will make an automatic redirect for all users attempting to access this github repo address to the new one.
Therefore in next future those who leave the project will be easily managed by others without changes for publication in Kodi.

- Use Github Transfer feature on this repo to your account
Similar to previous point but in to your @MoojMidge account, in order preserve branches/Issues/PR and redirect.

- Keep current repo
You become contributor of this repo this means that you will have access to manage all things of this repository (push commits directly, manage PRs, Issues, etc...),
I also suggest to backup current branch to a new branch name something like "upnext_v1.1.6".

This makes it easier for users to have a solid reference
that is better than having a project that changes github account every time a maintainer leaves the project

**Comment by MoojMidge** [comment]
1000 commits and lots of mistakes... it was an exercise in learning Python and Git.

Merging, transferring or just contributing to existing, either way suits me fine, I don't seek to impose. I'll leave it up to @im85288 do decide what they want to do.

**Comment by notoco** [comment]
I think it's a good idea.

**Comment by im85288** [comment]
@MoojMidge I have added you as a collaborator to this repository. I think initially it would be good to carry on with this version as there have been other major contributors @dagwieers being a major one who introduced a lot of cool features and improved the release strategy so still want to allow for the possibility of them returning at some stage. 

Please feel free to release to Kodi repo as and when you feel fit and thank you as always for stepping in and helping this addon continue it's long life cycle!

We can always review later down the line if you feel working on two versions becomes painful....or of course merge your changes into this one. 

I hope that satisfies everyone.

**Comment by dagwieers** [comment]
We can move this project to https://github.com/add-ons, we discussed this before but never decided to do it. We can keep the access rules etc. in-place.

Personally, I think it would be best so it is more a collaborative effort, as people come and go. And we do not have to move the location of the add-on when nee maintainers come into the picture.

Just let me know, and we can set it up.

**Comment by MoojMidge** [comment]
@im85288 Sounds good. I'll just try to get a release based on the latest code and fixes and can take it from there if anything else is needed

**Comment by MoojMidge** [comment]
@im85288 it looks like the GH_USERNAME and/or GH_TOKEN secrets used in the release workflow don't work anymore. Maybe the personal access token used in GH_TOKEN has expired or doesn't have the right permissions? Are you able to check when you get a chance?

Also I messed up the version bump - pushed rather submitting a PR. Will do it properly next time.

**Comment by im85288** [comment]
@MoojMidge I have had a look at the GH_TOKEN and GH_USERNAME and as far as I can tell it is automatically populated: https://docs.github.com/en/actions/security-guides/automatic-token-authentication Will keep digging but as far as I have seen this value is not set manually

**Comment by MoojMidge** [comment]
The GITHUB_ prefixed secrets are automatically created, but I think the GH_ prefixed secrets used in the release workflow must have been manually created at some point, probably because they are used to pull/push repo-scripts and required additional permissions to do so.

I'm just guessing based on the workflow (maybe @dagwieers will know more?), but I think the following will be needed:

GH_USERNAME should be "im85288"
GH_TOKEN should be [created](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions) to meet the [requirements of the addon-submitter action](https://github.com/xbmc/action-kodi-addon-submitter#gh_token)
EMAIL should be your email to meet the [requirements of the addon-submitter action](https://github.com/xbmc/action-kodi-addon-submitter#email)

**Comment by CastagnaIT** [comment]
in repo Enviroments setting page you can try re-create GH_USERNAME secret variable
or else replace
`GH_USERNAME: ${{secrets.GH_USERNAME}}`
with:
`GH_USERNAME: ${{ github.actor }}`

**Comment by michaelarnauts** [comment]
I think you should always use the ` ${{secrets.GH_USERNAME}}` variable, since if I remember correctly, this is the user that will create the PR in the Kodi repository, and they expect all releases to be made by the original author.

**Comment by im85288** [comment]
Thanks all, I have re-created `GH_USERNAME` @MoojMidge when you can please try again

**Comment by CastagnaIT** [comment]
thank you i see that the new release has been published
feel free to close this issue
