### ISSUE TITLE
Simple Pop-up not displaying correctly. 

### ISSUE THREAD

**Issue by dGstone18** [im85288/service.upnext#272]
When using the simple pop-up, the next episode button displays the following: "HIDE COLLECTION (SET) MARKS SECONDS", rather than the expected "Next Episode in X Seconds". This happens on every show and with the sample in the developer options. The Fancy pop-up works as expected. For context I am using this with PlexKodiConnect and the Amber skin. Any ideas?

**Comment by dGstone18** [comment]
After testing, this appears to be an issue caused by Amber.

**Comment by im85288** [comment]
If you compare what is in the skins folder for the simple upnext xml that should give a clue as to what has gone wrong. The author of Amber will be able to resolve it if you point it out to him.

**Comment by dGstone18** [comment]
I'll take a look. Appreciate the response.
