### ISSUE TITLE
Error Hardware Acceleration

### ISSUE THREAD

**Issue by googemyster** [im85288/service.upnext#276]
On some episodes if Hardware Acceleration is enabled the "up next" freezes screen after selecting "Watch Now" but continues to play next episode. Unable to see next episode but can hear it. Stoping video and playing manually works, turning off Hardware Acceleration works. Any Ideas? I must be able to have Hardware Acceleration on...

https://user-images.githubusercontent.com/109884453/180629698-ff146530-aeb5-4117-a93a-594b527053cd.mp4

.

**Comment by MoojMidge** [comment]
I think this is the same problem reported here: https://github.com/im85288/service.upnext/issues/263

Problem is not present on all platforms, but needs a fix in Kodi. If you are using Android a potential fix was identified, so if one of the Kodi developers has the opportunity to look at the bug report then hopefully it can be resolved.

**Comment by MoojMidge** [comment]
Duplicate of #263
