### ISSUE TITLE
Add an option to disable the "Still there?" popup

### ISSUE THREAD

**Issue by ArtyIF** [im85288/service.upnext#283]
My mom is watching/listening to the TV shows in the background while doing things, so it's quite a bit annoying to have to select the new episodes manually when the "Still there?" popup shows up. I set the "Number of episodes before "Still there?" query" setting to 15, but I would like to disable that altogether.

**Comment by MoojMidge** [comment]
Check if #284 does what you want, by changing `Number of episodes before "Still there?" query` setting to 0

**Comment by ArtyIF** [comment]
Yes it is
