### ISSUE TITLE
Option for next episode button 

### ISSUE THREAD

**Issue by Roy416** [im85288/service.upnext#301]
If I were to watch an episode through the In progress UpNext widget, in the video OSD, it shows the stop button, instead of the next episode button. Would be nice if there was an option to toggle if the stop button or next episode button should show, or both would be great.

**Comment by MoojMidge** [comment]
Crystal ball is broken so I have no idea what you are talking about with what little information you have provided.

Regardless, this addon doesn't have any widgets and has no control over the Video OSD.

**Comment by Roy416** [comment]
When you run the addon, you get this screen with the widgets. These aren't available with the official addon. Maybe you'll need the crystal ball working to figure out what that means. Also included a video of setting up the widget I'm talking about.

![image](https://github.com/im85288/service.upnext/assets/19165926/afe239fd-05de-46c0-9536-e49cdbe473f5)
https://imgur.com/3l1394o

**Comment by MoojMidge** [comment]
All good, but it doesn't change the fact that I still don't know what you are talking about.

If you wan't to provide more details to avoid the guessing game, create an issue [here](https://github.com/MoojMidge/service.upnext/issues).
