### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by calvin4242** [im85288/service.upnext#319]
Hello,
Cannot install this addon it uses python 2.25.0 . Needed Python 3 for Kodi 21 please.

**Comment by MoojMidge** [comment]
You should install the addon from the Kodi repository or install the correct version manually from https://github.com/im85288/service.upnext/releases

**Comment by calvin4242** [comment]
👋 Already installed last version 1.1.9 from May 10, 2023 for Kodi Matrix! This is why i come to ask here. But I don't understand this version for Matrix is Python 3.11 ready? Why I got this error on Coreelec 21.1.1?

EDIT: Installed directly from Kodi repo v1.1.9+matrix and it worked. Don't ask me why...thank you MoojMidge
