### ISSUE TITLE
Automatic Short Play Not Working

### ISSUE THREAD

**Issue by zang74** [im85288/service.upnext#36]
Hi Ian.

I've had this problem for a bit and hadn't had much of a chance to look at it myself (I created the original "automatic play short videos" PR), but see a lot has changed under the hood and I'm not *that* competent a python coder to grok all that's going on here now. Anyhow, I decided to try after your updates of the last few days (dled directly from GitHub today), but it still seemingly exists.

The problem:  
Having the time set and playing a video shorter than that will not automatically move to the next, regardless of whether the on screen notification is displayed. It's autoplaying (and logging) regular videos just fine. Short videos however, it just drops out of the player as it would without Up Next installed. And there's nothing in the logs to indicate why.

**Comment by im85288** [comment]
Hi Zang,

There’s a check in monitor.py that does not enable the addon for any videos less than 3 minutes long. Is the short play video you mention less than that time? I could remove the check as it was just to stop it messing with trailers etc.

**Comment by zang74** [comment]
Thanks, Ian.

It was actually set for 300 seconds/5 minutes. Removing that line from monitor.py locally seems to have resolved that problem.

Your trailer skipping functionality need not be lost though, as the “official” Kodi trailer naming convention is “moviename-trailer.ext”. Filtering out by the inclusion of “-trailer.[ext]” should do the same for most cases.

**Comment by im85288** [comment]
Ah yes 300 seconds, been a long time since I looked at the code! I will remove that check for the next release as it probably causes more confusion than I originally anticipated. Thanks for confirming all is good.

**Comment by zang74** [comment]
No problem.

I did however find that UpNext threw an error when disabling/reenabling. Upon disabling, I got a "check log files for details" error with the following in the log:

`2019-05-21 15:57:56.905 T:3688825712   ERROR: EXCEPTION: Unknown addon id 'service.upnext'.
2019-05-21 15:57:56.906 T:3688825712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'service.upnext'.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.upnext/service.py", line 4, in <module>
                                                Monitor().run()
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 51, in run
                                                self.log("======== STOP %s ========" % utils.addon_name(), 0)
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/utils.py", line 18, in addon_name
                                                return xbmcaddon.Addon().getAddonInfo('name').upper()
                                            RuntimeError: Unknown addon id 'service.upnext'.
                                            -->End of Python script error report<--`

**Comment by im85288** [comment]
Thanks I'll look into it, no idea at the moment what it could be

**Comment by im85288** [comment]
I checked in a change to monitor.py, please see if that resolves it for you. I'll not be around for a couple of days, but we will get this resolved :)

**Comment by angelblue05** [comment]
@im85288 
What was the change? I do not see it?

**Comment by im85288** [comment]
Just to change the log line where it says STOP above to not use the addon name, perhaps I forgot to push! Checking now

**Comment by zang74** [comment]
I spoke too soon re: the 300 seconds line. All that seems to do is allow the notification to come up. Silly me I didn't see if it'd follow through. Apparently it doesn't.

I have confirmed the issue is with the short play routine, as everything works fine when short play is disabled (including short videos that previously wouldn't automatically play the next).

**Comment by im85288** [comment]
Yes forgot to push! Should be there now

**Comment by im85288** [comment]
@zang74 - It's bed time for me, hopefully pick it up at the weekend unless @angelblue05 has any better ideas as she is more familiar with the code at the moment. Thanks

**Comment by angelblue05** [comment]
If Ian’s changes does not resolve your scenario, how would I go about to replicate it on my side?

**Comment by zang74** [comment]
I should give some background on my setup, if it helps. I'm on an Odroid N2, running CoreELEC 9.0 nightlies, serving media from a separate Linux Emby server via Emby for Kodi (native paths). Previously, I was running the same setup and having the same error on an Odroid C2, running CE 9.0 stable builds.

There are two issues at play here.

The first is that the autoplay of short videos doesn't seem to be functioning properly (ie; at all).

To replicate this one:
1) Go into Up Next settings-> Advanced and turn on "automatically play short videos". 
2) Download a series with episode length shorter than the "Maximum length for automatic short video play (in minutes)" setting, or set the number to more than 22 or 30 and test on regular TV series.
[Note: "Show onscreen notification during short video autoplay" doesn't seem to make a difference, but leaving it on helps know the notification's actually getting triggered" ]

How it should work:
I added this function as a PR to "Next Up" a couple of years back as a way of appeasing my young daughter, who loved and still loves, web shorts. Videos could be played automatically in sequence, without interruption and indefinitely, and with the option of displaying the notification or not, but all the while still maintaining its original function for us grownups and our "normal" length TV shows and series. The next episode isn't getting played. It acts like vanilla Kodi and just drops back to list view at the end.

All that said, going through my logs, I am getting a "Notice" right before the "CVideoPlayer::OnExit()". I seem to have missed it earlier as I'd filtered out Notices trying to find the errors: 

> NOTICE: UP NEXT Monitor -> log : Exception in Playback Monitor Service: UnboundLocalError("local variable 'should_play_non_default' referenced before assignment",)

Issue two showed up when I disabled the Up Next Addon to remove the ">300" bit mentioned above in the third post. I've never had a need to disable the Addon, but when I did I got the Python exception. Even after Ian's update today, it's still happening.

To replicate: Disable the Addon from the Addon info page. A notification comes up saying error and check the logs. A python exception like this shows up:

> 2019-05-21 23:01:40.598 T:3690922864   ERROR: EXCEPTION: Unknown addon id 'service.upnext'.
> 2019-05-21 23:01:40.600 T:3690922864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>  Error Type: <type 'exceptions.RuntimeError'>
>  Error Contents: Unknown addon id 'service.upnext'.
>  Traceback (most recent call last):
>  File "/storage/.kodi/addons/service.upnext/service.py", line 4, in <module>
>  Monitor().run()
>  File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 51, in run
>  self.log("======== STOP service.upnext ========", 0)
>  File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 18, in log
>  utils.log("%s %s" % (utils.addon_name(), class_name), str(msg), int(lvl))
>  File "/storage/.kodi/addons/service.upnext/resources/lib/utils.py", line 18, in addon_name
>  return xbmcaddon.Addon().getAddonInfo('name').upper()
>  RuntimeError: Unknown addon id 'service.upnext'.
> -->End of Python script error report<--

**Comment by angelblue05** [comment]
What version of Emby for Kodi are you running? There was a bug with the beta version that broke up next with native path. I’ve since fixed it, let me know.

I will try it out thanks.

**Comment by angelblue05** [comment]
https://github.com/im85288/service.upnext/pull/38

**Comment by zang74** [comment]
As of the fixes today, this seems to work. Though for the record, I'm on Emby for Kodi 4.0.24a, and running server 4.2.0.6.

I'm also fine with the disabling error. Unless it stops the disabling from actually happening (it doesn't), it's kinda moot. That said, if the error notification didn't come up it'd be even better.

**Comment by angelblue05** [comment]
The right way to disable up next is within the addon settings. There’s no way to stop that popup if you disable it via Kodi.

Glad it is working.
