### ISSUE TITLE
 No title or thumbnail - Netflix and Upnext

### ISSUE THREAD

**Issue by notoco** [im85288/service.upnext#45]
I am not really sure if the problem concerns the Netflix add-in or the UpNext add-on, but it seems to me that the problem is caused by the Netflix addition of all parameters to UpNext . Just in case, I will inform you in both places. When playing some shows such as The Ranch, the Notification window from the UpNext add-in does not receive either a thumbnail or the correct title (as in the screenshot). On other series that I checked works without any problems.
The playback of the next title itself works.
I attach the logs on the original skin.
Versions of UpNext and Netflix addons - the last master of git
Full log:
https://pastebin.pl/view/d81feef3

**Comment by im85288** [comment]
Hi,

This is 100 percent an issue with the Netflix addon not sending the image across correctly. This addon displays what it is given so has no control. Creating an issue on the Netflix github is the only way to resolve this. I will close this now but please reopen if you find there is actually an issue I need to deal with.

**Comment by notoco** [comment]
Of course I did it, suspecting it was Netflix's fault / netflix add-on
https://github.com/CastagnaIT/plugin.video.netflix/issues/105

**Comment by notoco** [comment]
And he fixed it.
