### ISSUE TITLE
If user configures to Stop on Close, it ought to say "Stop"

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#63]
Currently the options are **Play next** or **Close**, but I think that is confusing if **Close** means **Stop playing**. So I would probably propose to display **Stop playing** (or maybe something better?) when the user has this configured in the settings.

**Comment by im85288** [comment]
For this one close just means close the pop up as it does not stop playback. This is for when the user simply wants to dismiss the dialog.

**Comment by dagwieers** [comment]
But, if the user has set that "Close" means it stops playing, I think the button should say "Stop playing". Because this confused me.

**Comment by dagwieers** [comment]
I don't mind fixing this if you agree.

**Comment by im85288** [comment]
Yes agreed, please do thanks

**Comment by dagwieers** [comment]
This is now implemented.
