### ISSUE TITLE
When next episode was already partly watched, a selection comes up

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#64]
So I noticed that if the next episode was already partly watched, Next Up causes a selection window to show in the background with the option to **Resume from 00:00:50** or **Play from beginning**.

But it appears grayed out in the background while the screen is waiting to start playing. Very weird.

**Comment by im85288** [comment]
Hmm very strange indeed, I have not seen this before..

**Comment by dagwieers** [comment]
I don't see an easy fix for this :-/
It really should be an option to **Player.Open** to force it from a specific position (i.e. 0).

**Comment by dagwieers** [comment]
I cannot seem to reproduce this, which makes it hard to impossible to test a fix.
