### ISSUE TITLE
Autoplay succeeded but no GUI feedback

### ISSUE THREAD

**Issue by caphm** [im85288/service.upnext#7]
Hi,

I'm trying to get integration with your addon working for the Netflix addon.

I've set everything up according to the wiki. The first pitfall was that the Signal must be sent _after_ playback has started (Netflix addon sends signals shortly before, due to delay in inputstream.adaptive), otherwise signal data will be overwritten with an empty dict in onPlaybackStarted method.
If you could make it possible, that signals sent shortly _before_ playback would work as well, that would be great. Most addons that initiate playback via setResolvedUrl will probably work this way, because once setResolvedUrl has been called, addon execution will cease. I've worked around this, so this is not an immediate issue.

However, I just can't get it to work. Debug log is here: https://pastebin.com/9ieRAE06

The signal is sent with all required data and properly received by your addon. I'm supplying notification_time, which is 76s in the example. At or around this time of playback, nothing happens until the episode finishes.
The log says `Up Next style autoplay succeeded.` but nothing after that. No GUI feedback, no Signal, nothing.

If you want to test yourself, check out the latest commit in https://github.com/asciidisco/plugin.video.netflix/pull/519 which contains the integration.

I've shortened the debug log a little because it exceeded the 512kb limit on pastebin.

Thanks in advance for your support!

**Comment by im85288** [comment]
Hi, 

I'll have more time to look/test at the weekend, but a quick look at the JSON sent across 

`{
  u'rating': 9,
  u'tvshowid': None,
  u'art': {
    u'tvshow.fanart': u'',
    u'thumb': u'https://occ-0-1335-1336.1.nflxso.net/art/e484f/829d2becc4bcb3a0c9ee5f4f3247af97fe2e484f.jpg',
    u'tvshow.clearart': u'',
    u'tvshow.landscape': u'',
    u'tvshow.poster': u'',
    u'tvshow.clearlogo': u''
  },
  u'title': u'Folge 2',
  u'season': 1,
  u'plot': u'Nach einem versuchten Anschlag auf die Schule, die auch Budds Kinder besuchen, vermutet Montague Verr\xe4ter im Ministerium. Doch auch sie befindet sich in der Schusslinie.',
  u'episodeid': None,
  u'firstaired': 2018,
  u'episode': 2,
  u'playcount': 0,
  u'showtitle': u'Bodyguard'
}`

Shows that the `episodeid` and `tvshowid` are None but both need to be supplied with valid values, for the 'tvshowid' you can get away with putting in the `showtitle` as it just needs to be unique between tv shows. The 'episodeid' needs to be unique for each episode (you may be able to use the `episode` for this)

If there is another debug log can you please follow the link [here](https://github.com/im85288/service.upnext/wiki/Report-a-Bug)

Cheers :)

**Comment by caphm** [comment]
Ah, good to know. So they're not required to be the episode or TV show is from the Kodi database?
If so I can easily supply the unique IDs from Netflix.

**Comment by im85288** [comment]
Yeah they can be anything aslong as they are consistent, eg the tvshowid remains the same for all the episodes in the tvshow. The episodeid just needs to be different for each episode.

**Comment by caphm** [comment]
OK, got it to work. Thanks for yor support.

There's one thing you need to adapt in the documentation:
When registering the AddonSignals slot for responding to play, one must set upnextprovider as the source_id.
Change `AddonSignals.registerSlot('plugin.video.random', 'plugin.video.random_play_action', self.play_action)` to `AddonSignals.registerSlot('upnextprovider', 'plugin.video.random_play_action', self.play_action)` in https://github.com/im85288/service.upnext/wiki/Responding-to-Play

**Comment by im85288** [comment]
Great thanks for the feedback I’ll get that updated. Cheers
