### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by colfin22** [im85288/service.upnext#8]
I'm using 0.1.4 in the latest emby for Kodi 3.1.34a using Embruary 18.5.3 on Android TV on a Nvidia Shield TV. The episode finished at about 21.53.

https://paste.kodi.tv/ohasayazeb

**Comment by angelblue05** [comment]
@im85288 let me know if it's something with emby for kodi. Works for me here.

**Comment by im85288** [comment]
@angelblue05  thanks, yes it does not appear to be something up with this addon. Although the log is too verbose (he/she must have also turned on debug in the general kodi settings) these two lines are significant:

`22:37:46.270 T:202505028848  NOTICE: UP NEXT Player -> logMsg : Got details of now playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":6,"genre":["Crime","Drama","Thriller"],"id":15436,"label":"Shadow Walker","playcount":0,"plotoutline":"","season":2,"showtitle":"The Red Road","tvshowid":403,"type":"episode"}}}`


`22:37:46.409 T:202505028848  NOTICE: UP NEXT Player -> logMsg : Got details of next up episode {u'jsonrpc': u'2.0', u'id': 1, u'result': {u'episodes': [{u'plot': u'The story follows a sheriff trying to police the small New Jersey town where he grew up and a nearby Native American settlement begins with a tragedy that impacts both factions of the area.', u'tvshowid': 403, u'dateadded': u'2018-08-16 22:36:09', u'episode': 1, u'rating': 7.5, u'season': 1, u'lastplayed': u'2018-11-01 22:15:23', u'episodeid': 15425, u'resume': {u'position': 0.0, u'total': 0.0}, u'label': u'1x01. Arise My Love, Shake Off This Dream', u'writer': [], u'firstaired': u'2014-02-27', u'title': u'Arise My Love, Shake Off This Dream', u'file': u'plugin://plugin.video.emby.tvshows/a5406e185a6c1621d4c4ad66ff726e7a/?dbid=15425&mode=play&id=72c212005a4eb02716c05bdedd96bb20&filename=The+Red+Road+-+S01E01+-+Arise+My+Love%2C+Shake+Off+This+Dream.mkv', u'art':, u'playcount': 0, u'runtime': 2660, u'showtitle': u'The Red Road', u'streamdetails': {u'video': [{u'language': u'', u'stereomode': u'', u'width': 1920, u'codec': u'h264', u'aspect': 1.7777780294418335, u'duration': 2660, u'height': 1080}], u'audio': [{u'channels': 6, u'codec': u'dts', u'language': u'eng'}], u'subtitle': []}}], u'limits': {u'start': 0, u'total': 12, u'end': 12}}}`

It seems like it is picking up the wrong episode, strange stuff

**Comment by colfin22** [comment]
That's strange, debug logging is not enabled in Kodi system settings

**Comment by im85288** [comment]
No problem, it would also be useful if you could try a couple of other episodes. Something seems strange with your setup.

Maybe @angelblue05 understands more.

**Comment by colfin22** [comment]
Fresh log

https://paste.kodi.tv/nufexozubu

**Comment by rossl87** [comment]
I'm having exactly the same issue - Kodi 18 (beta 5) - latest Emby for Kodi and Up Next 0.1.4. @im85288  your comment about picking up the wrong episode is correct. the popup is not appearing and if after an episode You select another (as it reverts to the home screen), when you select any new episode, it plays the previous episode again. I'll try and sort out some logs this weekend.

**Comment by angelblue05** [comment]
That's just an unrelated widget issue. What platform is Kodi running on? Try playing from within the library. Does the issue exists?

**Comment by colfin22** [comment]
The opening post has all the details of the system and versions. I guess I should've said I was playing from the up next widget on the home screen. I will try from within a series later and report back.

**Comment by rossl87** [comment]
@angelblue05 @colinfin2 @im85288 

Interesting - For me, if I play from the next up widget, Up Next does not work. If I play from the series, it works. 

That's on Windows 10, Kodi 18 b5 with latest Emby for Kodi beta.

**Comment by im85288** [comment]
Good find guys, @angelblue05 the second log seems to have an empty serverid..not sure if that makes any difference

**Comment by colfin22** [comment]
I just watched a last episode in a season from season view, it did not work to offer up next the first episode of the next season. I didn't realise it was the last episode I will try again later.

Here is the log anyway
https://paste.kodi.tv/somucadete

**Comment by im85288** [comment]
@colfin22 in your latest log it does have the playcounts included and did find the next episode in season 3 to play. However I'm guessing it is not being offered to be played up next as it has already been watched (playcounts are high). Up next only works out the box for unwatched episodes, you can turn on include watched in the settings so that it works for watched episodes.

**Comment by colfin22** [comment]
This was my first time to watch the episode I watched, the last in season 2. The next episode, the first in season 3 has also never been watched.

**Comment by im85288** [comment]
Ok thanks we have to wait for @angelblue05 to check the data as it shows `playcount': 2` for the next episode (season 3 episode 1), and `playcount': 5` for the current episode (season 2 episode 12)

**Comment by colfin22** [comment]
I can confirm 0.1.5 is working playing from the next up widget on the homescreen (not the same show as before mind you).
I will try another show now

**Comment by im85288** [comment]
Excellent, the problems all seem to be related to the playcount setting in the data provided.

**Comment by colfin22** [comment]
I just watched season 3 episode 1 from the next up widget and it did not work

https://paste.kodi.tv/umosijafus

**Comment by im85288** [comment]
For now you can set the include watched setting to true in the up next settings. But yes ultimately we need to see what @angelblue05 makes of it

**Comment by colfin22** [comment]
This add-on is working as it should when I enable the include watched. Should I choose it?

@angelblue05 do you want me to open a new issue about the play count? If so where? I can provide whatever logs you need.

**Comment by angelblue05** [comment]
The playcount value comes from emby itself. However, can you grab your kodi log, enable debug in the addon settings only. Repeat the test. 

I will correct playcount None in the addon.

**Comment by im85288** [comment]
@colfin22 I’m going to close this issue so please carry on your debugging into the play count on the Emby forums. If it turns out to be an issue with this addon then you can reopen or create a new issue. Thanks
