### ISSUE TITLE
Request : Episode duration / Ends time

### ISSUE THREAD

**Issue by angus2064** [im85288/service.upnext#81]
Hello !
In my opinion ,that could be a great upgrade to add to the fancy panel the duration of the next episode or even better the ends time (Ends At : 8:00am). 
If this could be possible to integer this feature to a future version that would be awesome. 
Thanks !

**Comment by dagwieers** [comment]
I would like to see some indication as well, however I don't know what would be the best way to show this visually. When I get the pop-up, often I simply would like to see what time it is. (*Is it time to go to bed?*)

So preferably I would like to see the same information that is shown in the Info pane during playback. Which shows:

> **[Time]** *(big)*
> Ends at: [Time]

However, that would not make it clear this is about the next episode, not the current. So maybe it would be better to show:

> **[Time]** *(big)*
> Next episode ends at: [Time]

So:

> **4:38** *(big)*
> Next episode ends at: 4:41

And does this include the current remaining time, or not ? (For Netflix I would say no, but for other episode maybe yes?)

**Comment by dagwieers** [comment]
I added my proposal in PR #153. Please test this so we can include it in the upcoming v1.1.0 release !
