### ISSUE TITLE
New release in the Kodi repository

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#87]
For the upcoming release of our add-on (**plugin.video.vrt.nu**) we would need a new release of Up Next to appear in the Kodi repositories. The current v1.0.1 is too old.

Can we work towards an imminent release?
And what would be required (wrt. testing, translations, etc.) in order to release a new version to the Kodi repository?

**Comment by im85288** [comment]
Yes sure I will get a test release out tomorrow. I think maybe a week or so of testing and then we can submit it to the kodi repo.

**Comment by dagwieers** [comment]
For the existing translations we have the following issues:
```
[dag@moria service.upnext]$ make language
= Starting language test
resources/language/resource.language.de_de/strings.po: warning: Charset missing in header.
                                                                Message conversion to user's charset will not work.
msgcmp: input file doesn't contain a header entry with a charset specification
resources/language/resource.language.fr_fr/strings.po:105: this message is untranslated
resources/language/resource.language.fr_fr/strings.po:173: this message is untranslated
resources/language/resource.language.fr_fr/strings.po:105: warning: this message is not used
resources/language/resource.language.fr_fr/strings.po:173: warning: this message is not used
msgcmp: found 2 fatal errors
resources/language/resource.language.hu_hu/strings.po:96: this message is untranslated
resources/language/resource.language.hu_hu/strings.po:164: this message is untranslated
resources/language/resource.language.hu_hu/strings.po:96: warning: this message is not used
resources/language/resource.language.hu_hu/strings.po:164: warning: this message is not used
msgcmp: found 2 fatal errors
resources/language/resource.language.it_it/strings.po:102: this message is untranslated
resources/language/resource.language.it_it/strings.po:166: this message is untranslated
resources/language/resource.language.it_it/strings.po:170: this message is untranslated
resources/language/resource.language.it_it/strings.po:102: warning: this message is not used
resources/language/resource.language.it_it/strings.po:166: warning: this message is not used
resources/language/resource.language.it_it/strings.po:170: warning: this message is not used
msgcmp: found 3 fatal errors
resources/language/resource.language.pl_pl/strings.po:117: this message is untranslated
resources/language/resource.language.pl_pl/strings.po:117: warning: this message is not used
msgcmp: found 1 fatal error
make: [language] Error 1 (ignored)
```
For the above we may ask our past translators to update the translations accordingly.

And I could check with our translators of **inputstreamhelper** if they would be interested in helping to translate **Up Next** to Greek, Russian and Swedish as well.

**Comment by im85288** [comment]
Yes that would be great, I need to get Transifex updated as some contributors have submitted changes there and others via github

**Comment by dagwieers** [comment]
@im85288 I am interested to learn how that integration works. :+1:

**Comment by im85288** [comment]
No probs I will post details tomorrow, in the middle of watching a movie at the moment :)

**Comment by dagwieers** [comment]
So we still have issues with French, Hungarian and Polish languages.
- French: 2 untranslated strings
- Hungarian: 2 untranslated strings &rarr; @frodo19 
- Polish: 1 untranslated string &rarr; @notoco

**Comment by frodo19** [comment]
Hungarian strings ready. 

> So we still have issues with French, Hungarian and Polish languages

> * Hungarian: 2 untranslated strings → @frodo19


Hungarian strings ready. :)

**Comment by notoco** [comment]
Done:
https://github.com/im85288/service.upnext/pull/99

**Comment by mediaminister** [comment]
French is also done: https://github.com/im85288/service.upnext/pull/101

**Comment by dagwieers** [comment]
I think we shouldn't hold off on releasing v1.0.6, we know that a large set of our users is affected by the change in Addon Signals and we have a fix for this. We should release that fix as soon as possible, knowing that the release process may take a few days to a week.

**Comment by im85288** [comment]
> I think we shouldn't hold off on releasing v1.0.6, we know that a large set of our users is affected by the change in Addon Signals and we have a fix for this. We should release that fix as soon as possible, knowing that the release process may take a few days to a week.

So we are ready to release to the kodi repo? Are we not wanting the settings changes included?

**Comment by dagwieers** [comment]
I don't think we want to hold off on releasing a fix for something that now breaks Up Next for users.

**Comment by dagwieers** [comment]
@im85288 I am getting frustrated knowing that Kodi users (mostly Netflix) have a broken binge watching experience and we are sitting on the fix for 11 days now. Can we please move forward with a release?

I can't do this myself as we have to merge a few things first. #107 and maybe #105 as well.

**Comment by im85288** [comment]
@dagwieers let's get this sorted now, been off work a couple of days due to some cold virus going round

**Comment by dagwieers** [comment]
@im85288 Thanks! For the v1.1.0 release I am asking translators of Netflix and inputstream-related projects to help out with each others projects.

**Comment by im85288** [comment]
@dagwieers cool PR is created here: https://github.com/xbmc/repo-scripts/pull/1217

**Comment by im85288** [comment]
There's an issue with the icon size: ERROR: Icon should have either 256x256 or 512x512 but it has 500x500

Is that easy for you to adjust?

**Comment by dagwieers** [comment]
Ouch. Yes, it's easy to fix. Hold on!

**Comment by im85288** [comment]
Do I need to include the pylintrc file?

WARN: Found non whitelisted file ending in filename ./service.upnext/.pylintrc

**Comment by dagwieers** [comment]
No, the only files needed are listed in the Makefile:
```Makefile
include_files = addon.xml default.py LICENSE README.md resources/ service.py
```

**Comment by im85288** [comment]
Cool will remove from the release

**Comment by dagwieers** [comment]
One way to do new releases is perform a `make zip`.
And then unzip over the existing directory in the xbmc/repo-scripts tree.

**Comment by dagwieers** [comment]
And maybe add it in the description for this update that this is an important/urgent fix for a recent breakage in changes to Addon Signals.

**Comment by im85288** [comment]
Sounds like a plan

**Comment by im85288** [comment]
We do not need requirements.txt either I guess?

git+git://github.com/dagwieers/script.module.addon.signals.git@setup.py#egg=AddonSignals

**Comment by dagwieers** [comment]
Nope, only that short list of files that also end up in the ZIP file.

**Comment by dagwieers** [comment]
@im85288 I still see too many files in your PR. 53 files is simply too much for this add-on
The following items need to go:
- Remove the **test/** directory, unwanted
- Remove **tox.ini**
- Remove **.codecov.yml**
- Remove **Makefile**

**Comment by im85288** [comment]
@dagwieers done now thanks

**Comment by dagwieers** [comment]
Thanks, we can close this now!

**Comment by dagwieers** [comment]
Things seem to be going well. I suspect about 1/3 deployment rate.
http://mirrors.kodi.tv/stats?downloadstats&filter=service.upnext

The total numbers include reinstallations, and in principle after 24 hours the majority of systems would be updated. It depends on how many systems are turned off/seldom used.

**Comment by im85288** [comment]
Yeah that’s a good uptake in 24 hours!

**Comment by mediaminister** [comment]
And no new issues yet. Well done!

**Comment by dagwieers** [comment]
*Knock on wood*
