### ISSUE TITLE
Automatic Intro Skipping does not work

### ISSUE THREAD

**Issue by MeCias** [im85288/service.upnext#9]
Hi,

just noticed that as soon you enable the automatic intro skipping function in the Netflix plug-in, the skipping function is not working no more after upnext started the new episode. If the automatic skipping (by default) is off you are able to manual skip.

**Comment by im85288** [comment]
Hi, that’s most likely an issue to report with the Netflix addon as it sounds like it does things differently when using this method of playback.

Incidentally I tested it earlier with manual auto skip so did not notice the problem. What I did notice is skip intro stays open if you seek forward past the intro time. That’s another bug that needs reported. I have an idea how to fix it so may let caphm know.

**Comment by caphm** [comment]
You can close this here, as it is indeed an issue with the netflix plugin. The feature is somewhat unreliable due to the way how Kodi propagates playback started events.

**Comment by MeCias** [comment]
Thanks
